/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) path_con_N_fun_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Printing routine */
#ifdef MATLAB_MEX_FILE
  #define PRINTF mexPrintf
#else
  #define PRINTF printf
#endif

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const int casadi_s0[40] = {36, 1, 0, 36, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35};
static const int casadi_s1[4] = {0, 1, 0, 0};
static const int casadi_s2[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

void casadi_fill(casadi_real* x, int n, casadi_real alpha) {
  int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const int* sp, casadi_real* w) {
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  int nrow = *sp++, ncol = *sp++, nnz = sp[ncol];
  const int *colind=sp, *row=sp+ncol+1;
  size_t p_nrow = mxGetM(p), p_ncol = mxGetN(p);
  int is_sparse = mxIsSparse(p);
  mwIndex *Jc, *Ir;
  if (is_sparse) {
#ifndef CASADI_MEX_NO_SPARSE
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
#else /* CASADI_MEX_NO_SPARSE */
    mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Sparse inputs disabled.");
#endif /* CASADI_MEX_NO_SPARSE */
  }
  const double* p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    casadi_fill(y, nnz, v);
  } else {
    int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Dimension mismatch.");
    }
    int r,c,k;
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const int* sp, const casadi_real* x) {
  int nrow = *sp++, ncol = *sp++, nnz = sp[ncol];
  const int *colind = sp, *row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  if (nnz!=nrow*ncol) {
    mxArray*p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    int i;
    mwIndex* j;
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      double* d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  mxArray* p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    double* d = (double*)mxGetData(p);
    int c, k;
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = to_double(*x++);
      }
    }
  }
  return p;
}

#endif

/* path_con_N_fun:(states[36],params[0])->(path_con_N[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][12] : 0;
  casadi_real a1=2.1267912134641990e+15;
  casadi_real a2=arg[0] ? arg[0][24] : 0;
  casadi_real a3=(-a2);
  a3=cos(a3);
  a3=(a1*a3);
  casadi_real a4=arg[0] ? arg[0][22] : 0;
  casadi_real a5=(-a4);
  a5=cos(a5);
  a3=(a3*a5);
  a5=9.0071992547409920e+15;
  a3=(a3/a5);
  a3=(a0+a3);
  casadi_real a6=5.9355102524963050e+15;
  casadi_real a7=arg[0] ? arg[0][26] : 0;
  casadi_real a8=(-a7);
  a8=cos(a8);
  a8=(a6*a8);
  casadi_real a9=(-a4);
  a9=sin(a9);
  a8=(a8*a9);
  a8=(a8/a5);
  a3=(a3-a8);
  a8=(-a4);
  a8=cos(a8);
  a8=(a6*a8);
  a9=(-a2);
  a9=sin(a9);
  a8=(a8*a9);
  a9=(-a7);
  a9=sin(a9);
  a8=(a8*a9);
  a8=(a8/a5);
  a3=(a3-a8);
  a8=4.6333999278562871e-01;
  a3=(a3+a8);
  a3=sq(a3);
  a8=arg[0] ? arg[0][13] : 0;
  a9=(-a7);
  a9=cos(a9);
  a9=(a6*a9);
  casadi_real a10=(-a4);
  a10=cos(a10);
  a9=(a9*a10);
  a9=(a9/a5);
  a9=(a8+a9);
  a10=(-a2);
  a10=cos(a10);
  a10=(a1*a10);
  casadi_real a11=(-a4);
  a11=sin(a11);
  a10=(a10*a11);
  a10=(a10/a5);
  a9=(a9+a10);
  a10=(-a2);
  a10=sin(a10);
  a10=(a6*a10);
  a11=(-a7);
  a11=sin(a11);
  a10=(a10*a11);
  a11=(-a4);
  a11=sin(a11);
  a10=(a10*a11);
  a10=(a10/a5);
  a9=(a9-a10);
  a10=1.0525284086833064e+00;
  a9=(a9-a10);
  a9=sq(a9);
  a3=(a3+a9);
  a9=arg[0] ? arg[0][14] : 0;
  a10=(-a2);
  a10=sin(a10);
  a1=(a1*a10);
  a1=(a1/a5);
  a1=(a9+a1);
  a10=(-a2);
  a10=cos(a10);
  a6=(a6*a10);
  a10=(-a7);
  a10=sin(a10);
  a6=(a6*a10);
  a6=(a6/a5);
  a1=(a1+a6);
  a6=9.0549999999999997e-01;
  a1=(a1+a6);
  a1=sq(a1);
  a3=(a3+a1);
  a3=sqrt(a3);
  if (res[0]!=0) res[0][0]=a3;
  a3=(-a7);
  a3=cos(a3);
  a1=(-a4);
  a1=sin(a1);
  a3=(a3*a1);
  a1=8.;
  a3=(a3/a1);
  a3=(a3-a0);
  a10=(-a4);
  a10=cos(a10);
  a11=(-a2);
  a11=sin(a11);
  a10=(a10*a11);
  a11=(-a7);
  a11=sin(a11);
  a10=(a10*a11);
  a10=(a10/a1);
  a3=(a3+a10);
  a10=2.7549954627911820e+01;
  a11=(-a2);
  a11=cos(a11);
  a11=(a10*a11);
  casadi_real a12=(-a4);
  a12=cos(a12);
  a11=(a11*a12);
  a12=40.;
  a11=(a11/a12);
  a3=(a3+a11);
  a11=6.7984634373173858e-01;
  a3=(a3-a11);
  a3=sq(a3);
  a11=(-a2);
  a11=cos(a11);
  casadi_real a13=(-a7);
  a13=sin(a13);
  a11=(a11*a13);
  a11=(a11/a1);
  a11=(a9+a11);
  a13=(-a2);
  a13=sin(a13);
  a13=(a10*a13);
  a13=(a13/a12);
  a11=(a11-a13);
  a11=(a11+a6);
  a11=sq(a11);
  a3=(a3+a11);
  a11=(-a2);
  a11=sin(a11);
  a13=(-a7);
  a13=sin(a13);
  a11=(a11*a13);
  a13=(-a4);
  a13=sin(a13);
  a11=(a11*a13);
  a11=(a11/a1);
  a13=(-a7);
  a13=cos(a13);
  casadi_real a14=(-a4);
  a14=cos(a14);
  a13=(a13*a14);
  a13=(a13/a1);
  a11=(a11-a13);
  a11=(a11-a8);
  a13=(-a2);
  a13=cos(a13);
  a13=(a10*a13);
  a14=(-a4);
  a14=sin(a14);
  a13=(a13*a14);
  a13=(a13/a12);
  a11=(a11+a13);
  a13=9.2752840868330644e-01;
  a11=(a11+a13);
  a11=sq(a11);
  a3=(a3+a11);
  a3=sqrt(a3);
  if (res[0]!=0) res[0][1]=a3;
  a3=(-a7);
  a3=cos(a3);
  a11=(-a4);
  a11=sin(a11);
  a3=(a3*a11);
  a3=(a3/a1);
  a3=(a0+a3);
  a11=(-a4);
  a11=cos(a11);
  a13=(-a2);
  a13=sin(a13);
  a11=(a11*a13);
  a13=(-a7);
  a13=sin(a13);
  a11=(a11*a13);
  a11=(a11/a1);
  a3=(a3+a11);
  a11=(-a2);
  a11=cos(a11);
  a11=(a10*a11);
  a13=(-a4);
  a13=cos(a13);
  a11=(a11*a13);
  a11=(a11/a12);
  a3=(a3-a11);
  a11=6.7984634373173913e-01;
  a3=(a3+a11);
  a3=sq(a3);
  a11=(-a7);
  a11=cos(a11);
  a13=(-a4);
  a13=cos(a13);
  a11=(a11*a13);
  a11=(a11/a1);
  a11=(a8-a11);
  a13=(-a2);
  a13=sin(a13);
  a14=(-a7);
  a14=sin(a14);
  a13=(a13*a14);
  a14=(-a4);
  a14=sin(a14);
  a13=(a13*a14);
  a13=(a13/a1);
  a11=(a11+a13);
  a13=(-a2);
  a13=cos(a13);
  a13=(a10*a13);
  a14=(-a4);
  a14=sin(a14);
  a13=(a13*a14);
  a13=(a13/a12);
  a11=(a11-a13);
  a13=9.2752840868330588e-01;
  a11=(a11+a13);
  a11=sq(a11);
  a3=(a3+a11);
  a11=(-a2);
  a11=cos(a11);
  a13=(-a7);
  a13=sin(a13);
  a11=(a11*a13);
  a11=(a11/a1);
  a11=(a9-a11);
  a1=(-a2);
  a1=sin(a1);
  a10=(a10*a1);
  a10=(a10/a12);
  a11=(a11-a10);
  a11=(a11+a6);
  a11=sq(a11);
  a3=(a3+a11);
  a3=sqrt(a3);
  if (res[0]!=0) res[0][2]=a3;
  a3=8.5071648538567790e+15;
  a11=(-a2);
  a11=sin(a11);
  a11=(a3*a11);
  a10=3.6028797018963968e+16;
  a11=(a11/a10);
  a11=(a9+a11);
  a12=5.9355102524963070e+15;
  a1=(-a2);
  a1=cos(a1);
  a1=(a12*a1);
  a13=(-a7);
  a13=sin(a13);
  a1=(a1*a13);
  a1=(a1/a5);
  a11=(a11-a1);
  a11=(a11+a6);
  a11=sq(a11);
  a1=(-a2);
  a1=cos(a1);
  a1=(a3*a1);
  a13=(-a4);
  a13=cos(a13);
  a1=(a1*a13);
  a1=(a1/a10);
  a1=(a0+a1);
  a13=(-a7);
  a13=cos(a13);
  a13=(a12*a13);
  a14=(-a4);
  a14=sin(a14);
  a13=(a13*a14);
  a13=(a13/a5);
  a1=(a1+a13);
  a13=(-a4);
  a13=cos(a13);
  a13=(a12*a13);
  a14=(-a2);
  a14=sin(a14);
  a13=(a13*a14);
  a14=(-a7);
  a14=sin(a14);
  a13=(a13*a14);
  a13=(a13/a5);
  a1=(a1+a13);
  a13=4.6333999278562921e-01;
  a1=(a1+a13);
  a1=sq(a1);
  a11=(a11+a1);
  a1=(-a7);
  a1=cos(a1);
  a1=(a12*a1);
  a13=(-a4);
  a13=cos(a13);
  a1=(a1*a13);
  a1=(a1/a5);
  a1=(a8-a1);
  a13=(-a2);
  a13=cos(a13);
  a3=(a3*a13);
  a13=(-a4);
  a13=sin(a13);
  a3=(a3*a13);
  a3=(a3/a10);
  a1=(a1+a3);
  a3=(-a2);
  a3=sin(a3);
  a12=(a12*a3);
  a3=(-a7);
  a3=sin(a3);
  a12=(a12*a3);
  a3=(-a4);
  a3=sin(a3);
  a12=(a12*a3);
  a12=(a12/a5);
  a1=(a1+a12);
  a12=1.0525284086833062e+00;
  a1=(a1+a12);
  a1=sq(a1);
  a11=(a11+a1);
  a11=sqrt(a11);
  if (res[0]!=0) res[0][3]=a11;
  a11=1.0192267640881710e+15;
  a1=(-a2);
  a1=cos(a1);
  a1=(a11*a1);
  a12=(-a4);
  a12=cos(a12);
  a1=(a1*a12);
  a12=2.2517998136852480e+15;
  a1=(a1/a12);
  a1=(a0+a1);
  a3=4.8096103456536850e+15;
  a10=(-a7);
  a10=cos(a10);
  a10=(a3*a10);
  a13=(-a4);
  a13=sin(a13);
  a10=(a10*a13);
  a10=(a10/a5);
  a1=(a1+a10);
  a10=1.1431863365173676e+00;
  a1=(a1-a10);
  a13=(-a4);
  a13=cos(a13);
  a13=(a3*a13);
  a14=(-a2);
  a14=sin(a14);
  a13=(a13*a14);
  a14=(-a7);
  a14=sin(a14);
  a13=(a13*a14);
  a13=(a13/a5);
  a1=(a1+a13);
  a1=sq(a1);
  a13=(-a7);
  a13=cos(a13);
  a13=(a3*a13);
  a14=(-a4);
  a14=cos(a14);
  a13=(a13*a14);
  a13=(a13/a5);
  a13=(a8-a13);
  a14=(-a2);
  a14=cos(a14);
  a14=(a11*a14);
  casadi_real a15=(-a4);
  a15=sin(a15);
  a14=(a14*a15);
  a14=(a14/a12);
  a13=(a13+a14);
  a14=(-a2);
  a14=sin(a14);
  a14=(a3*a14);
  a15=(-a7);
  a15=sin(a15);
  a14=(a14*a15);
  a15=(-a4);
  a15=sin(a15);
  a14=(a14*a15);
  a14=(a14/a5);
  a13=(a13+a14);
  a14=1.2500000000000000e-01;
  a13=(a13+a14);
  a13=sq(a13);
  a1=(a1+a13);
  a13=(-a2);
  a13=sin(a13);
  a11=(a11*a13);
  a11=(a11/a12);
  a11=(a9+a11);
  a12=(-a2);
  a12=cos(a12);
  a3=(a3*a12);
  a12=(-a7);
  a12=sin(a12);
  a3=(a3*a12);
  a3=(a3/a5);
  a11=(a11-a3);
  a11=(a11+a6);
  a11=sq(a11);
  a1=(a1+a11);
  a1=sqrt(a1);
  if (res[0]!=0) res[0][4]=a1;
  a1=3.0060064660335500e+14;
  a11=(-a7);
  a11=cos(a11);
  a11=(a1*a11);
  a3=(-a4);
  a3=cos(a3);
  a11=(a11*a3);
  a3=5.6294995342131200e+14;
  a11=(a11/a3);
  a8=(a8+a11);
  a11=8.1538141127053790e+15;
  a5=(-a2);
  a5=cos(a5);
  a5=(a11*a5);
  a12=(-a4);
  a12=sin(a12);
  a5=(a5*a12);
  a12=1.8014398509481984e+16;
  a5=(a5/a12);
  a8=(a8+a5);
  a5=(-a2);
  a5=sin(a5);
  a5=(a1*a5);
  a13=(-a7);
  a13=sin(a13);
  a5=(a5*a13);
  a13=(-a4);
  a13=sin(a13);
  a5=(a5*a13);
  a5=(a5/a3);
  a8=(a8-a5);
  a8=(a8-a14);
  a8=sq(a8);
  a14=(-a2);
  a14=sin(a14);
  a14=(a11*a14);
  a14=(a14/a12);
  a9=(a9+a14);
  a14=(-a2);
  a14=cos(a14);
  a14=(a1*a14);
  a5=(-a7);
  a5=sin(a5);
  a14=(a14*a5);
  a14=(a14/a3);
  a9=(a9+a14);
  a9=(a9+a6);
  a9=sq(a9);
  a8=(a8+a9);
  a9=(-a7);
  a9=cos(a9);
  a9=(a1*a9);
  a6=(-a4);
  a6=sin(a6);
  a9=(a9*a6);
  a9=(a9/a3);
  a6=(-a2);
  a6=cos(a6);
  a11=(a11*a6);
  a6=(-a4);
  a6=cos(a6);
  a11=(a11*a6);
  a11=(a11/a12);
  a9=(a9-a11);
  a9=(a9-a0);
  a9=(a9+a10);
  a4=(-a4);
  a4=cos(a4);
  a1=(a1*a4);
  a2=(-a2);
  a2=sin(a2);
  a1=(a1*a2);
  a7=(-a7);
  a7=sin(a7);
  a1=(a1*a7);
  a1=(a1/a3);
  a9=(a9+a1);
  a9=sq(a9);
  a8=(a8+a9);
  a8=sqrt(a8);
  if (res[0]!=0) res[0][5]=a8;
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_N_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT int path_con_N_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* path_con_N_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_N_fun_name_out(int i){
  switch (i) {
    case 0: return "path_con_N";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_N_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_N_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 16;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_path_con_N_fun(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  int i, j;
  if (argc>2) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"path_con_N_fun\" failed. Too many input arguments (%d, max 2)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"path_con_N_fun\" failed. Too many output arguments (%d, max 1)", resc);
  int *iw = 0;
  casadi_real w[78];
  const casadi_real* arg[2] = {0};
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+42);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+36, casadi_s1, w+42);
  casadi_real* res[1] = {0};
  --resc;
  res[0] = w+36;
  i = path_con_N_fun(arg, res, iw, w+42, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"path_con_N_fun\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s2, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[15];
  int buf_ok = --argc >= 0 && !mxGetString(*argv++, buf, sizeof(buf));
  if (!buf_ok) {
    /* name error */
  } else if (strcmp(buf, "path_con_N_fun")==0) {
    return mex_path_con_N_fun(resc, resv, argc, argv);
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'path_con_N_fun'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
