/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Simulate_system_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Printing routine */
#ifdef MATLAB_MEX_FILE
  #define PRINTF mexPrintf
#else
  #define PRINTF printf
#endif

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const int casadi_s0[36] = {32, 1, 0, 32, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31};
static const int casadi_s1[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const int casadi_s2[4] = {0, 1, 0, 0};

void casadi_fill(casadi_real* x, int n, casadi_real alpha) {
  int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const int* sp, casadi_real* w) {
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  int nrow = *sp++, ncol = *sp++, nnz = sp[ncol];
  const int *colind=sp, *row=sp+ncol+1;
  size_t p_nrow = mxGetM(p), p_ncol = mxGetN(p);
  int is_sparse = mxIsSparse(p);
  mwIndex *Jc, *Ir;
  if (is_sparse) {
#ifndef CASADI_MEX_NO_SPARSE
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
#else /* CASADI_MEX_NO_SPARSE */
    mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Sparse inputs disabled.");
#endif /* CASADI_MEX_NO_SPARSE */
  }
  const double* p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    casadi_fill(y, nnz, v);
  } else {
    int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Dimension mismatch.");
    }
    int r,c,k;
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const int* sp, const casadi_real* x) {
  int nrow = *sp++, ncol = *sp++, nnz = sp[ncol];
  const int *colind = sp, *row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  if (nnz!=nrow*ncol) {
    mxArray*p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    int i;
    mwIndex* j;
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      double* d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  mxArray* p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    double* d = (double*)mxGetData(p);
    int c, k;
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = to_double(*x++);
      }
    }
  }
  return p;
}

#endif

/* Simulate_system:(states[32],controls[7],params[0])->(xf[32]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][0] : 0;
  casadi_real a1=8.3333333333333339e-004;
  casadi_real a2=-1.8702006980802793e-001;
  casadi_real a3=(a2*a0);
  casadi_real a4=arg[0] ? arg[0][1] : 0;
  a3=(a3+a4);
  casadi_real a5=arg[0] ? arg[0][8] : 0;
  casadi_real a6=(a2*a5);
  a3=(a3+a6);
  a6=2.;
  casadi_real a7=2.5000000000000001e-003;
  casadi_real a8=(a7*a3);
  a8=(a0+a8);
  casadi_real a9=(a2*a8);
  casadi_real a10=-2.1815008726003490e-003;
  casadi_real a11=(a10*a0);
  casadi_real a12=(a10*a5);
  a11=(a11+a12);
  a12=(a7*a11);
  a12=(a4+a12);
  a9=(a9+a12);
  a12=arg[1] ? arg[1][1] : 0;
  casadi_real a13=(a7*a12);
  a13=(a5+a13);
  casadi_real a14=(a2*a13);
  a9=(a9+a14);
  a14=(a6*a9);
  a3=(a3+a14);
  a9=(a7*a9);
  a9=(a0+a9);
  a14=(a2*a9);
  a8=(a10*a8);
  casadi_real a15=(a10*a13);
  a8=(a8+a15);
  a15=(a7*a8);
  a15=(a4+a15);
  a14=(a14+a15);
  a15=(a7*a12);
  a15=(a5+a15);
  casadi_real a16=(a2*a15);
  a14=(a14+a16);
  a16=(a6*a14);
  a3=(a3+a16);
  a16=5.0000000000000001e-003;
  a14=(a16*a14);
  a14=(a0+a14);
  casadi_real a17=(a2*a14);
  a9=(a10*a9);
  casadi_real a18=(a10*a15);
  a9=(a9+a18);
  a18=(a16*a9);
  a18=(a4+a18);
  a17=(a17+a18);
  a18=(a16*a12);
  a18=(a5+a18);
  casadi_real a19=(a2*a18);
  a17=(a17+a19);
  a3=(a3+a17);
  a3=(a1*a3);
  a0=(a0+a3);
  if (res[0]!=0) res[0][0]=a0;
  a8=(a6*a8);
  a11=(a11+a8);
  a9=(a6*a9);
  a11=(a11+a9);
  a14=(a10*a14);
  a9=(a10*a18);
  a14=(a14+a9);
  a11=(a11+a14);
  a11=(a1*a11);
  a4=(a4+a11);
  if (res[0]!=0) res[0][1]=a4;
  a4=arg[0] ? arg[0][2] : 0;
  a11=-2.0000000000000001e-001;
  a14=(a11*a4);
  a9=7.8480000000000005e-001;
  a8=arg[0] ? arg[0][4] : 0;
  a0=(a9*a8);
  a14=(a14+a0);
  a0=-8.0000000000000002e-002;
  a3=arg[0] ? arg[0][7] : 0;
  a17=(a0*a3);
  a14=(a14+a17);
  a17=(a7*a14);
  a17=(a4+a17);
  a17=(a11*a17);
  a19=(a7*a5);
  a19=(a8+a19);
  a19=(a9*a19);
  a17=(a17+a19);
  a19=arg[1] ? arg[1][0] : 0;
  casadi_real a20=(a7*a19);
  a20=(a3+a20);
  casadi_real a21=(a0*a20);
  a17=(a17+a21);
  a21=(a6*a17);
  a14=(a14+a21);
  a17=(a7*a17);
  a17=(a4+a17);
  a17=(a11*a17);
  a21=(a7*a13);
  a21=(a8+a21);
  a21=(a9*a21);
  a17=(a17+a21);
  a21=(a7*a19);
  a21=(a3+a21);
  casadi_real a22=(a0*a21);
  a17=(a17+a22);
  a22=(a6*a17);
  a14=(a14+a22);
  a17=(a16*a17);
  a17=(a4+a17);
  a17=(a11*a17);
  a22=(a16*a15);
  a22=(a8+a22);
  a9=(a9*a22);
  a17=(a17+a9);
  a9=(a16*a19);
  a9=(a3+a9);
  a22=(a0*a9);
  a17=(a17+a22);
  a14=(a14+a17);
  a14=(a1*a14);
  a4=(a4+a14);
  if (res[0]!=0) res[0][2]=a4;
  a4=arg[0] ? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a4;
  a13=(a6*a13);
  a13=(a5+a13);
  a15=(a6*a15);
  a13=(a13+a15);
  a13=(a13+a18);
  a13=(a1*a13);
  a8=(a8+a13);
  if (res[0]!=0) res[0][4]=a8;
  a8=arg[0] ? arg[0][5] : 0;
  a13=arg[0] ? arg[0][6] : 0;
  a18=(a7*a3);
  a18=(a13+a18);
  a18=(a6*a18);
  a18=(a13+a18);
  a15=(a7*a20);
  a15=(a13+a15);
  a15=(a6*a15);
  a18=(a18+a15);
  a15=(a16*a21);
  a15=(a13+a15);
  a18=(a18+a15);
  a18=(a1*a18);
  a8=(a8+a18);
  if (res[0]!=0) res[0][5]=a8;
  a8=(a6*a20);
  a8=(a3+a8);
  a18=(a6*a21);
  a8=(a8+a18);
  a8=(a8+a9);
  a8=(a1*a8);
  a13=(a13+a8);
  if (res[0]!=0) res[0][6]=a13;
  a13=(a6*a19);
  a13=(a19+a13);
  a8=(a6*a19);
  a13=(a13+a8);
  a13=(a13+a19);
  a13=(a1*a13);
  a13=(a3+a13);
  if (res[0]!=0) res[0][7]=a13;
  a13=(a6*a12);
  a13=(a12+a13);
  a19=(a6*a12);
  a13=(a13+a19);
  a13=(a13+a12);
  a13=(a1*a13);
  a5=(a5+a13);
  if (res[0]!=0) res[0][8]=a5;
  a5=arg[0] ? arg[0][9] : 0;
  a13=(a2*a5);
  a12=arg[0] ? arg[0][10] : 0;
  a13=(a13+a12);
  a19=arg[0] ? arg[0][17] : 0;
  a8=(a2*a19);
  a13=(a13+a8);
  a8=(a7*a13);
  a8=(a5+a8);
  a18=(a2*a8);
  a15=(a10*a5);
  a4=(a10*a19);
  a15=(a15+a4);
  a4=(a7*a15);
  a4=(a12+a4);
  a18=(a18+a4);
  a4=arg[1] ? arg[1][3] : 0;
  a14=(a7*a4);
  a14=(a19+a14);
  a17=(a2*a14);
  a18=(a18+a17);
  a17=(a6*a18);
  a13=(a13+a17);
  a18=(a7*a18);
  a18=(a5+a18);
  a17=(a2*a18);
  a8=(a10*a8);
  a22=(a10*a14);
  a8=(a8+a22);
  a22=(a7*a8);
  a22=(a12+a22);
  a17=(a17+a22);
  a22=(a7*a4);
  a22=(a19+a22);
  casadi_real a23=(a2*a22);
  a17=(a17+a23);
  a23=(a6*a17);
  a13=(a13+a23);
  a17=(a16*a17);
  a17=(a5+a17);
  a23=(a2*a17);
  a18=(a10*a18);
  casadi_real a24=(a10*a22);
  a18=(a18+a24);
  a24=(a16*a18);
  a24=(a12+a24);
  a23=(a23+a24);
  a24=(a16*a4);
  a24=(a19+a24);
  casadi_real a25=(a2*a24);
  a23=(a23+a25);
  a13=(a13+a23);
  a13=(a1*a13);
  a5=(a5+a13);
  if (res[0]!=0) res[0][9]=a5;
  a8=(a6*a8);
  a15=(a15+a8);
  a18=(a6*a18);
  a15=(a15+a18);
  a17=(a10*a17);
  a18=(a10*a24);
  a17=(a17+a18);
  a15=(a15+a17);
  a15=(a1*a15);
  a12=(a12+a15);
  if (res[0]!=0) res[0][10]=a12;
  a12=arg[0] ? arg[0][11] : 0;
  a15=(a11*a12);
  a17=-7.8480000000000005e-001;
  a18=arg[0] ? arg[0][13] : 0;
  a8=(a17*a18);
  a15=(a15+a8);
  a8=arg[0] ? arg[0][16] : 0;
  a5=(a0*a8);
  a15=(a15+a5);
  a5=(a7*a15);
  a5=(a12+a5);
  a5=(a11*a5);
  a13=(a7*a19);
  a13=(a18+a13);
  a23=(a17*a13);
  a5=(a5+a23);
  a23=arg[1] ? arg[1][2] : 0;
  a25=(a7*a23);
  a25=(a8+a25);
  casadi_real a26=(a0*a25);
  a5=(a5+a26);
  a26=(a6*a5);
  a15=(a15+a26);
  a5=(a7*a5);
  a5=(a12+a5);
  a5=(a11*a5);
  a26=(a7*a14);
  a26=(a18+a26);
  casadi_real a27=(a17*a26);
  a5=(a5+a27);
  a27=(a7*a23);
  a27=(a8+a27);
  casadi_real a28=(a0*a27);
  a5=(a5+a28);
  a28=(a6*a5);
  a15=(a15+a28);
  a5=(a16*a5);
  a5=(a12+a5);
  a5=(a11*a5);
  a28=(a16*a22);
  a28=(a18+a28);
  a17=(a17*a28);
  a5=(a5+a17);
  a17=(a16*a23);
  a17=(a8+a17);
  casadi_real a29=(a0*a17);
  a5=(a5+a29);
  a15=(a15+a5);
  a15=(a1*a15);
  a12=(a12+a15);
  if (res[0]!=0) res[0][11]=a12;
  a12=arg[0] ? arg[0][12] : 0;
  if (res[0]!=0) res[0][12]=a12;
  a14=(a6*a14);
  a14=(a19+a14);
  a22=(a6*a22);
  a14=(a14+a22);
  a14=(a14+a24);
  a14=(a1*a14);
  a14=(a18+a14);
  if (res[0]!=0) res[0][13]=a14;
  a14=arg[0] ? arg[0][14] : 0;
  a24=arg[0] ? arg[0][15] : 0;
  a22=(a7*a8);
  a22=(a24+a22);
  a22=(a6*a22);
  a22=(a24+a22);
  a12=(a7*a25);
  a12=(a24+a12);
  a12=(a6*a12);
  a22=(a22+a12);
  a12=(a16*a27);
  a12=(a24+a12);
  a22=(a22+a12);
  a22=(a1*a22);
  a14=(a14+a22);
  if (res[0]!=0) res[0][14]=a14;
  a14=(a6*a25);
  a14=(a8+a14);
  a22=(a6*a27);
  a14=(a14+a22);
  a14=(a14+a17);
  a14=(a1*a14);
  a24=(a24+a14);
  if (res[0]!=0) res[0][15]=a24;
  a24=(a6*a23);
  a24=(a23+a24);
  a14=(a6*a23);
  a24=(a24+a14);
  a24=(a24+a23);
  a24=(a1*a24);
  a24=(a8+a24);
  if (res[0]!=0) res[0][16]=a24;
  a24=(a6*a4);
  a24=(a4+a24);
  a23=(a6*a4);
  a24=(a24+a23);
  a24=(a24+a4);
  a24=(a1*a24);
  a19=(a19+a24);
  if (res[0]!=0) res[0][17]=a19;
  a19=arg[0] ? arg[0][18] : 0;
  a24=(a11*a19);
  a4=arg[0] ? arg[0][22] : 0;
  a23=(a0*a4);
  a24=(a24+a23);
  a23=(a7*a24);
  a23=(a19+a23);
  a23=(a11*a23);
  a14=arg[1] ? arg[1][4] : 0;
  a22=(a7*a14);
  a22=(a4+a22);
  a12=(a0*a22);
  a23=(a23+a12);
  a12=(a6*a23);
  a24=(a24+a12);
  a23=(a7*a23);
  a23=(a19+a23);
  a23=(a11*a23);
  a12=(a7*a14);
  a12=(a4+a12);
  a15=(a0*a12);
  a23=(a23+a15);
  a15=(a6*a23);
  a24=(a24+a15);
  a23=(a16*a23);
  a23=(a19+a23);
  a11=(a11*a23);
  a23=(a16*a14);
  a23=(a4+a23);
  a0=(a0*a23);
  a11=(a11+a0);
  a24=(a24+a11);
  a24=(a1*a24);
  a19=(a19+a24);
  if (res[0]!=0) res[0][18]=a19;
  a19=arg[0] ? arg[0][19] : 0;
  if (res[0]!=0) res[0][19]=a19;
  a19=arg[0] ? arg[0][20] : 0;
  a24=arg[0] ? arg[0][21] : 0;
  a11=(a7*a4);
  a11=(a24+a11);
  a11=(a6*a11);
  a11=(a24+a11);
  a0=(a7*a22);
  a0=(a24+a0);
  a0=(a6*a0);
  a11=(a11+a0);
  a0=(a16*a12);
  a0=(a24+a0);
  a11=(a11+a0);
  a11=(a1*a11);
  a19=(a19+a11);
  if (res[0]!=0) res[0][20]=a19;
  a22=(a6*a22);
  a22=(a4+a22);
  a12=(a6*a12);
  a22=(a22+a12);
  a22=(a22+a23);
  a22=(a1*a22);
  a24=(a24+a22);
  if (res[0]!=0) res[0][21]=a24;
  a24=(a6*a14);
  a24=(a14+a24);
  a22=(a6*a14);
  a24=(a24+a22);
  a24=(a24+a14);
  a24=(a1*a24);
  a4=(a4+a24);
  if (res[0]!=0) res[0][22]=a4;
  a4=arg[0] ? arg[0][23] : 0;
  a24=(a2*a4);
  a14=arg[0] ? arg[0][24] : 0;
  a24=(a24+a14);
  a22=arg[0] ? arg[0][26] : 0;
  a23=(a2*a22);
  a24=(a24+a23);
  a23=(a7*a24);
  a23=(a4+a23);
  a12=(a2*a23);
  a19=(a10*a4);
  a11=(a10*a22);
  a19=(a19+a11);
  a11=(a7*a19);
  a11=(a14+a11);
  a12=(a12+a11);
  a11=arg[1] ? arg[1][5] : 0;
  a0=(a7*a11);
  a0=(a22+a0);
  a15=(a2*a0);
  a12=(a12+a15);
  a15=(a6*a12);
  a24=(a24+a15);
  a12=(a7*a12);
  a12=(a4+a12);
  a15=(a2*a12);
  a23=(a10*a23);
  a5=(a10*a0);
  a23=(a23+a5);
  a5=(a7*a23);
  a5=(a14+a5);
  a15=(a15+a5);
  a5=(a7*a11);
  a5=(a22+a5);
  a29=(a2*a5);
  a15=(a15+a29);
  a29=(a6*a15);
  a24=(a24+a29);
  a15=(a16*a15);
  a15=(a4+a15);
  a29=(a2*a15);
  a12=(a10*a12);
  casadi_real a30=(a10*a5);
  a12=(a12+a30);
  a30=(a16*a12);
  a30=(a14+a30);
  a29=(a29+a30);
  a30=(a16*a11);
  a30=(a22+a30);
  a2=(a2*a30);
  a29=(a29+a2);
  a24=(a24+a29);
  a24=(a1*a24);
  a4=(a4+a24);
  if (res[0]!=0) res[0][23]=a4;
  a23=(a6*a23);
  a19=(a19+a23);
  a12=(a6*a12);
  a19=(a19+a12);
  a15=(a10*a15);
  a10=(a10*a30);
  a15=(a15+a10);
  a19=(a19+a15);
  a19=(a1*a19);
  a14=(a14+a19);
  if (res[0]!=0) res[0][24]=a14;
  a14=arg[0] ? arg[0][25] : 0;
  a0=(a6*a0);
  a0=(a22+a0);
  a5=(a6*a5);
  a0=(a0+a5);
  a0=(a0+a30);
  a0=(a1*a0);
  a14=(a14+a0);
  if (res[0]!=0) res[0][25]=a14;
  a14=(a6*a11);
  a14=(a11+a14);
  a0=(a6*a11);
  a14=(a14+a0);
  a14=(a14+a11);
  a14=(a1*a14);
  a22=(a22+a14);
  if (res[0]!=0) res[0][26]=a22;
  a22=arg[0] ? arg[0][27] : 0;
  a14=arg[0] ? arg[0][28] : 0;
  a11=200.;
  a0=10.;
  a30=(a0*a22);
  a30=sq(a30);
  a30=(a11*a30);
  a5=2000.;
  a30=(a30+a5);
  a19=67.;
  a30=(a30/a19);
  a30=(a30*a14);
  a15=12000.;
  a10=(a0*a22);
  a10=sq(a10);
  a10=(a15*a10);
  a12=1000.;
  a10=(a10+a12);
  a10=(a10*a22);
  a10=(a10/a19);
  a30=(a30+a10);
  a8=(a8-a30);
  a30=9.8100000000000005e+000;
  a18=(a30*a18);
  a8=(a8+a18);
  a18=10000.;
  a10=arg[0] ? arg[0][29] : 0;
  a23=(a18*a10);
  a23=(a23/a19);
  a8=(a8-a23);
  a23=(a7*a8);
  a23=(a14+a23);
  a4=(a6*a23);
  a4=(a14+a4);
  a24=(a7*a14);
  a24=(a22+a24);
  a29=(a0*a24);
  a29=sq(a29);
  a29=(a11*a29);
  a29=(a29+a5);
  a29=(a29/a19);
  a29=(a29*a23);
  a2=(a0*a24);
  a2=sq(a2);
  a2=(a15*a2);
  a2=(a2+a12);
  a2=(a2*a24);
  a2=(a2/a19);
  a29=(a29+a2);
  a25=(a25-a29);
  a13=(a30*a13);
  a25=(a25+a13);
  a13=fabs(a14);
  a13=(a13*a10);
  a29=30.;
  a2=3.1830988618379069e-001;
  casadi_real a31=9.8480775301220802e-001;
  a3=(a19*a3);
  a3=(a31*a3);
  casadi_real a32=8.5174431145629327e+001;
  a3=(a3+a32);
  a3=atan(a3);
  a3=(a2*a3);
  casadi_real a33=5.9999999999999998e-001;
  a3=(a3+a33);
  casadi_real a34=(a29*a3);
  casadi_real a35=15.;
  a3=(a35*a3);
  casadi_real a36=(a14/a16);
  a36=sq(a36);
  a36=(-a36);
  a36=exp(a36);
  a3=(a3*a36);
  a34=(a34+a3);
  a34=(a34/a18);
  a13=(a13/a34);
  a13=(a14-a13);
  a34=(a7*a13);
  a34=(a10+a34);
  a3=(a18*a34);
  a3=(a3/a19);
  a25=(a25-a3);
  a3=(a7*a25);
  a3=(a14+a3);
  a36=(a6*a3);
  a4=(a4+a36);
  a36=(a7*a23);
  a36=(a22+a36);
  casadi_real a37=(a0*a36);
  a37=sq(a37);
  a37=(a11*a37);
  a37=(a37+a5);
  a37=(a37/a19);
  a37=(a37*a3);
  casadi_real a38=(a0*a36);
  a38=sq(a38);
  a38=(a15*a38);
  a38=(a38+a12);
  a38=(a38*a36);
  a38=(a38/a19);
  a37=(a37+a38);
  a27=(a27-a37);
  a26=(a30*a26);
  a27=(a27+a26);
  a26=fabs(a23);
  a26=(a26*a34);
  a20=(a19*a20);
  a20=(a31*a20);
  a20=(a20+a32);
  a20=atan(a20);
  a20=(a2*a20);
  a20=(a20+a33);
  a34=(a29*a20);
  a20=(a35*a20);
  a37=(a23/a16);
  a37=sq(a37);
  a37=(-a37);
  a37=exp(a37);
  a20=(a20*a37);
  a34=(a34+a20);
  a34=(a34/a18);
  a26=(a26/a34);
  a26=(a23-a26);
  a7=(a7*a26);
  a7=(a10+a7);
  a34=(a18*a7);
  a34=(a34/a19);
  a27=(a27-a34);
  a34=(a16*a27);
  a34=(a14+a34);
  a4=(a4+a34);
  a4=(a1*a4);
  a4=(a22+a4);
  if (res[0]!=0) res[0][27]=a4;
  a25=(a6*a25);
  a8=(a8+a25);
  a27=(a6*a27);
  a8=(a8+a27);
  a27=(a16*a3);
  a27=(a22+a27);
  a25=(a0*a27);
  a25=sq(a25);
  a11=(a11*a25);
  a11=(a11+a5);
  a11=(a11/a19);
  a11=(a11*a34);
  a0=(a0*a27);
  a0=sq(a0);
  a15=(a15*a0);
  a15=(a15+a12);
  a15=(a15*a27);
  a15=(a15/a19);
  a11=(a11+a15);
  a17=(a17-a11);
  a30=(a30*a28);
  a17=(a17+a30);
  a30=fabs(a3);
  a30=(a30*a7);
  a21=(a19*a21);
  a21=(a31*a21);
  a21=(a21+a32);
  a21=atan(a21);
  a21=(a2*a21);
  a21=(a21+a33);
  a7=(a29*a21);
  a21=(a35*a21);
  a28=(a3/a16);
  a28=sq(a28);
  a28=(-a28);
  a28=exp(a28);
  a21=(a21*a28);
  a7=(a7+a21);
  a7=(a7/a18);
  a30=(a30/a7);
  a30=(a3-a30);
  a7=(a16*a30);
  a7=(a10+a7);
  a21=(a18*a7);
  a21=(a21/a19);
  a17=(a17-a21);
  a8=(a8+a17);
  a8=(a1*a8);
  a8=(a14+a8);
  if (res[0]!=0) res[0][28]=a8;
  a26=(a6*a26);
  a13=(a13+a26);
  a30=(a6*a30);
  a13=(a13+a30);
  a30=fabs(a34);
  a30=(a30*a7);
  a19=(a19*a9);
  a31=(a31*a19);
  a31=(a31+a32);
  a31=atan(a31);
  a2=(a2*a31);
  a2=(a2+a33);
  a29=(a29*a2);
  a35=(a35*a2);
  a16=(a34/a16);
  a16=sq(a16);
  a16=(-a16);
  a16=exp(a16);
  a35=(a35*a16);
  a29=(a29+a35);
  a29=(a29/a18);
  a30=(a30/a29);
  a30=(a34-a30);
  a13=(a13+a30);
  a13=(a1*a13);
  a10=(a10+a13);
  if (res[0]!=0) res[0][29]=a10;
  a10=arg[0] ? arg[0][30] : 0;
  a13=2400000.;
  a30=sq(a22);
  a30=(a13*a30);
  a30=(a30*a14);
  a29=1200000.;
  a22=sq(a22);
  a22=(a29*a22);
  a22=(a22+a12);
  a22=(a22*a14);
  a30=(a30+a22);
  a22=arg[1] ? arg[1][6] : 0;
  a30=(a30+a22);
  a14=sq(a24);
  a14=(a13*a14);
  a14=(a14*a23);
  a24=sq(a24);
  a24=(a29*a24);
  a24=(a24+a12);
  a24=(a24*a23);
  a14=(a14+a24);
  a14=(a14+a22);
  a14=(a6*a14);
  a30=(a30+a14);
  a14=sq(a36);
  a14=(a13*a14);
  a14=(a14*a3);
  a36=sq(a36);
  a36=(a29*a36);
  a36=(a36+a12);
  a36=(a36*a3);
  a14=(a14+a36);
  a14=(a14+a22);
  a14=(a6*a14);
  a30=(a30+a14);
  a14=sq(a27);
  a13=(a13*a14);
  a13=(a13*a34);
  a27=sq(a27);
  a29=(a29*a27);
  a29=(a29+a12);
  a29=(a29*a34);
  a13=(a13+a29);
  a13=(a13+a22);
  a30=(a30+a13);
  a30=(a1*a30);
  a10=(a10+a30);
  if (res[0]!=0) res[0][30]=a10;
  a10=arg[0] ? arg[0][31] : 0;
  a30=(a6*a22);
  a30=(a22+a30);
  a6=(a6*a22);
  a30=(a30+a6);
  a30=(a30+a22);
  a1=(a1*a30);
  a10=(a10+a1);
  if (res[0]!=0) res[0][31]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int Simulate_system(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void Simulate_system_incref(void) {
}

CASADI_SYMBOL_EXPORT void Simulate_system_decref(void) {
}

CASADI_SYMBOL_EXPORT int Simulate_system_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int Simulate_system_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* Simulate_system_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Simulate_system_name_out(int i){
  switch (i) {
    case 0: return "xf";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Simulate_system_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Simulate_system_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Simulate_system_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 39;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_Simulate_system(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  int i, j;
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"Simulate_system\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"Simulate_system\" failed. Too many output arguments (%d, max 1)", resc);
  int *iw = 0;
  casadi_real w[110];
  const casadi_real* arg[3] = {0};
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+71);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+32, casadi_s1, w+71);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+39, casadi_s2, w+71);
  casadi_real* res[1] = {0};
  --resc;
  res[0] = w+39;
  i = Simulate_system(arg, res, iw, w+71, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"Simulate_system\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s0, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[16];
  int buf_ok = --argc >= 0 && !mxGetString(*argv++, buf, sizeof(buf));
  if (!buf_ok) {
    /* name error */
  } else if (strcmp(buf, "Simulate_system")==0) {
    return mex_Simulate_system(resc, resv, argc, argv);
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'Simulate_system'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
