/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Simulate_system_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Printing routine */
#ifdef MATLAB_MEX_FILE
  #define PRINTF mexPrintf
#else
  #define PRINTF printf
#endif

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const int casadi_s0[40] = {36, 1, 0, 36, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35};
static const int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const int casadi_s2[4] = {0, 1, 0, 0};

void casadi_fill(casadi_real* x, int n, casadi_real alpha) {
  int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const int* sp, casadi_real* w) {
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  int nrow = *sp++, ncol = *sp++, nnz = sp[ncol];
  const int *colind=sp, *row=sp+ncol+1;
  size_t p_nrow = mxGetM(p), p_ncol = mxGetN(p);
  int is_sparse = mxIsSparse(p);
  mwIndex *Jc, *Ir;
  if (is_sparse) {
#ifndef CASADI_MEX_NO_SPARSE
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
#else /* CASADI_MEX_NO_SPARSE */
    mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Sparse inputs disabled.");
#endif /* CASADI_MEX_NO_SPARSE */
  }
  const double* p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    casadi_fill(y, nnz, v);
  } else {
    int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError","\"from_mex\" failed: Dimension mismatch.");
    }
    int r,c,k;
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const int* sp, const casadi_real* x) {
  int nrow = *sp++, ncol = *sp++, nnz = sp[ncol];
  const int *colind = sp, *row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  if (nnz!=nrow*ncol) {
    mxArray*p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    int i;
    mwIndex* j;
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      double* d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  mxArray* p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    double* d = (double*)mxGetData(p);
    int c, k;
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = to_double(*x++);
      }
    }
  }
  return p;
}

#endif

/* Simulate_system:(states[36],controls[6],params[0])->(xf[36]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][0] : 0;
  casadi_real a1=1.6666666666666668e-03;
  casadi_real a2=-6.2699999999999996e+01;
  casadi_real a3=(a2*a0);
  casadi_real a4=-1.2500000000000000e+01;
  casadi_real a5=arg[0] ? arg[0][1] : 0;
  casadi_real a6=(a4*a5);
  a3=(a3+a6);
  a6=arg[0] ? arg[0][28] : 0;
  casadi_real a7=cos(a6);
  casadi_real a8=arg[0] ? arg[0][22] : 0;
  casadi_real a9=cos(a8);
  casadi_real a10=arg[0] ? arg[0][24] : 0;
  casadi_real a11=cos(a10);
  casadi_real a12=(a9*a11);
  casadi_real a13=(a7*a12);
  casadi_real a14=sin(a6);
  casadi_real a15=sin(a8);
  a11=(a15*a11);
  casadi_real a16=(a14*a11);
  a13=(a13-a16);
  a16=6.6525263313334859e-01;
  casadi_real a17=arg[0] ? arg[0][32] : 0;
  casadi_real a18=(a16*a17);
  casadi_real a19=5.9190703818405445e-02;
  casadi_real a20=arg[1] ? arg[1][0] : 0;
  casadi_real a21=(a19*a20);
  a18=(a18+a21);
  casadi_real a22=-6.6525263313334859e-01;
  casadi_real a23=arg[0] ? arg[0][30] : 0;
  casadi_real a24=(a22*a23);
  casadi_real a25=9.4080929618159459e-01;
  casadi_real a26=(a25*a20);
  a24=(a24+a26);
  casadi_real a27=(a7*a24);
  casadi_real a28=arg[0] ? arg[0][31] : 0;
  casadi_real a29=(a22*a28);
  casadi_real a30=arg[1] ? arg[1][1] : 0;
  casadi_real a31=(a25*a30);
  a29=(a29+a31);
  casadi_real a32=(a14*a29);
  a27=(a27-a32);
  a27=(a18+a27);
  a32=2.;
  casadi_real a33=arg[0] ? arg[0][29] : 0;
  casadi_real a34=sin(a6);
  casadi_real a35=arg[0] ? arg[0][15] : 0;
  casadi_real a36=(a34*a35);
  casadi_real a37=cos(a6);
  casadi_real a38=arg[0] ? arg[0][16] : 0;
  casadi_real a39=(a37*a38);
  a36=(a36+a39);
  a36=(a33*a36);
  a36=(a32*a36);
  a27=(a27-a36);
  a13=(a13*a27);
  a12=(a34*a12);
  a11=(a37*a11);
  a12=(a12+a11);
  a11=arg[0] ? arg[0][33] : 0;
  a36=(a16*a11);
  a39=(a19*a30);
  a36=(a36+a39);
  casadi_real a40=(a34*a24);
  casadi_real a41=(a37*a29);
  a40=(a40+a41);
  a40=(a36+a40);
  a41=(a7*a35);
  casadi_real a42=(a14*a38);
  a41=(a41-a42);
  a41=(a33*a41);
  a41=(a32*a41);
  a40=(a40+a41);
  a12=(a12*a40);
  a13=(a13+a12);
  a12=sin(a10);
  a41=arg[1] ? arg[1][2] : 0;
  a12=(a12*a41);
  a13=(a13-a12);
  a12=-9.8100000000000005e+00;
  a42=sin(a8);
  casadi_real a43=arg[0] ? arg[0][26] : 0;
  casadi_real a44=sin(a43);
  casadi_real a45=(a42*a44);
  casadi_real a46=sin(a10);
  a9=(a9*a46);
  casadi_real a47=cos(a43);
  casadi_real a48=(a9*a47);
  a45=(a45+a48);
  a48=(a12*a45);
  a13=(a13+a48);
  a3=(a3+a13);
  a13=5.0000000000000001e-03;
  a48=(a13*a3);
  a48=(a0+a48);
  casadi_real a49=(a2*a48);
  casadi_real a50=(a13*a0);
  a50=(a5+a50);
  a50=(a4*a50);
  a49=(a49+a50);
  a50=(a13*a33);
  a50=(a6+a50);
  casadi_real a51=cos(a50);
  casadi_real a52=arg[0] ? arg[0][23] : 0;
  casadi_real a53=(a13*a52);
  a53=(a8+a53);
  casadi_real a54=cos(a53);
  casadi_real a55=arg[0] ? arg[0][25] : 0;
  casadi_real a56=(a13*a55);
  a56=(a10+a56);
  casadi_real a57=cos(a56);
  casadi_real a58=(a54*a57);
  casadi_real a59=(a51*a58);
  casadi_real a60=sin(a50);
  casadi_real a61=sin(a53);
  a57=(a61*a57);
  casadi_real a62=(a60*a57);
  a59=(a59-a62);
  a62=-1.2599575146467862e+01;
  casadi_real a63=(a62*a17);
  casadi_real a64=1.7818490052273816e+01;
  casadi_real a65=(a64*a20);
  a63=(a63+a65);
  casadi_real a66=(a13*a63);
  a66=(a17+a66);
  casadi_real a67=(a16*a66);
  a67=(a67+a21);
  casadi_real a68=(a62*a23);
  a20=(a64*a20);
  a68=(a68+a20);
  casadi_real a69=(a13*a68);
  a69=(a23+a69);
  casadi_real a70=(a22*a69);
  a70=(a70+a26);
  casadi_real a71=(a51*a70);
  casadi_real a72=(a62*a28);
  casadi_real a73=(a64*a30);
  a72=(a72+a73);
  casadi_real a74=(a13*a72);
  a74=(a28+a74);
  casadi_real a75=(a22*a74);
  a75=(a75+a31);
  casadi_real a76=(a60*a75);
  a71=(a71-a76);
  a71=(a67+a71);
  a76=arg[0] ? arg[0][35] : 0;
  casadi_real a77=(a16*a76);
  casadi_real a78=arg[1] ? arg[1][3] : 0;
  a19=(a19*a78);
  a77=(a77+a19);
  casadi_real a79=(a13*a77);
  a79=(a33+a79);
  casadi_real a80=sin(a50);
  casadi_real a81=(a13*a24);
  a81=(a35+a81);
  casadi_real a82=(a80*a81);
  a50=cos(a50);
  casadi_real a83=(a13*a29);
  a83=(a38+a83);
  casadi_real a84=(a50*a83);
  a82=(a82+a84);
  a82=(a79*a82);
  a82=(a32*a82);
  a71=(a71-a82);
  a59=(a59*a71);
  a58=(a80*a58);
  a57=(a50*a57);
  a58=(a58+a57);
  a57=(a62*a11);
  a30=(a64*a30);
  a57=(a57+a30);
  a82=(a13*a57);
  a82=(a11+a82);
  a84=(a16*a82);
  a84=(a84+a39);
  casadi_real a85=(a80*a70);
  casadi_real a86=(a50*a75);
  a85=(a85+a86);
  a85=(a84+a85);
  a86=(a51*a81);
  casadi_real a87=(a60*a83);
  a86=(a86-a87);
  a86=(a79*a86);
  a86=(a32*a86);
  a85=(a85+a86);
  a58=(a58*a85);
  a59=(a59+a58);
  a58=sin(a56);
  a58=(a58*a41);
  a59=(a59-a58);
  a58=sin(a53);
  a86=arg[0] ? arg[0][27] : 0;
  a87=(a13*a86);
  a87=(a43+a87);
  casadi_real a88=sin(a87);
  casadi_real a89=(a58*a88);
  casadi_real a90=sin(a56);
  a54=(a54*a90);
  casadi_real a91=cos(a87);
  casadi_real a92=(a54*a91);
  a89=(a89+a92);
  a92=(a12*a89);
  a59=(a59+a92);
  a49=(a49+a59);
  a59=(a32*a49);
  a3=(a3+a59);
  a49=(a13*a49);
  a49=(a0+a49);
  a59=(a2*a49);
  a92=(a13*a48);
  a92=(a5+a92);
  a92=(a4*a92);
  a59=(a59+a92);
  a92=(a13*a79);
  a92=(a6+a92);
  casadi_real a93=cos(a92);
  casadi_real a94=arg[0] ? arg[0][34] : 0;
  casadi_real a95=(a22*a94);
  a25=(a25*a78);
  a95=(a95+a25);
  casadi_real a96=(a13*a95);
  a96=(a52+a96);
  casadi_real a97=(a13*a96);
  a97=(a8+a97);
  casadi_real a98=cos(a97);
  casadi_real a99=arg[1] ? arg[1][4] : 0;
  casadi_real a100=(a13*a99);
  a100=(a55+a100);
  casadi_real a101=(a13*a100);
  a101=(a10+a101);
  casadi_real a102=cos(a101);
  casadi_real a103=(a98*a102);
  casadi_real a104=(a93*a103);
  casadi_real a105=sin(a92);
  casadi_real a106=sin(a97);
  a102=(a106*a102);
  casadi_real a107=(a105*a102);
  a104=(a104-a107);
  a66=(a62*a66);
  a66=(a66+a65);
  a107=(a13*a66);
  a107=(a17+a107);
  casadi_real a108=(a16*a107);
  a108=(a108+a21);
  a69=(a62*a69);
  a69=(a69+a20);
  casadi_real a109=(a13*a69);
  a109=(a23+a109);
  casadi_real a110=(a22*a109);
  a110=(a110+a26);
  casadi_real a111=(a93*a110);
  a74=(a62*a74);
  a74=(a74+a73);
  casadi_real a112=(a13*a74);
  a112=(a28+a112);
  casadi_real a113=(a22*a112);
  a113=(a113+a31);
  casadi_real a114=(a105*a113);
  a111=(a111-a114);
  a111=(a108+a111);
  a114=(a62*a76);
  casadi_real a115=(a64*a78);
  a114=(a114+a115);
  casadi_real a116=(a13*a114);
  a116=(a76+a116);
  casadi_real a117=(a16*a116);
  a117=(a117+a19);
  casadi_real a118=(a13*a117);
  a118=(a33+a118);
  casadi_real a119=sin(a92);
  casadi_real a120=(a13*a70);
  a120=(a35+a120);
  casadi_real a121=(a119*a120);
  a92=cos(a92);
  casadi_real a122=(a13*a75);
  a122=(a38+a122);
  casadi_real a123=(a92*a122);
  a121=(a121+a123);
  a121=(a118*a121);
  a121=(a32*a121);
  a111=(a111-a121);
  a104=(a104*a111);
  a103=(a119*a103);
  a102=(a92*a102);
  a103=(a103+a102);
  a82=(a62*a82);
  a82=(a82+a30);
  a102=(a13*a82);
  a102=(a11+a102);
  a121=(a16*a102);
  a121=(a121+a39);
  a123=(a119*a110);
  casadi_real a124=(a92*a113);
  a123=(a123+a124);
  a123=(a121+a123);
  a124=(a93*a120);
  casadi_real a125=(a105*a122);
  a124=(a124-a125);
  a124=(a118*a124);
  a124=(a32*a124);
  a123=(a123+a124);
  a103=(a103*a123);
  a104=(a104+a103);
  a103=sin(a101);
  a103=(a103*a41);
  a104=(a104-a103);
  a103=sin(a97);
  a124=arg[1] ? arg[1][5] : 0;
  a125=(a13*a124);
  a125=(a86+a125);
  casadi_real a126=(a13*a125);
  a126=(a43+a126);
  casadi_real a127=sin(a126);
  casadi_real a128=(a103*a127);
  casadi_real a129=sin(a101);
  a98=(a98*a129);
  casadi_real a130=cos(a126);
  casadi_real a131=(a98*a130);
  a128=(a128+a131);
  a131=(a12*a128);
  a104=(a104+a131);
  a59=(a59+a104);
  a104=(a32*a59);
  a3=(a3+a104);
  a104=1.0000000000000000e-02;
  a59=(a104*a59);
  a59=(a0+a59);
  a131=(a2*a59);
  casadi_real a132=(a104*a49);
  a132=(a5+a132);
  a132=(a4*a132);
  a131=(a131+a132);
  a132=(a104*a118);
  a132=(a6+a132);
  casadi_real a133=cos(a132);
  casadi_real a134=(a62*a94);
  a64=(a64*a78);
  a134=(a134+a64);
  a78=(a13*a134);
  a78=(a94+a78);
  casadi_real a135=(a22*a78);
  a135=(a135+a25);
  casadi_real a136=(a13*a135);
  a136=(a52+a136);
  casadi_real a137=(a104*a136);
  a137=(a8+a137);
  casadi_real a138=cos(a137);
  casadi_real a139=(a13*a99);
  a139=(a55+a139);
  casadi_real a140=(a104*a139);
  a140=(a10+a140);
  casadi_real a141=cos(a140);
  casadi_real a142=(a138*a141);
  casadi_real a143=(a133*a142);
  casadi_real a144=sin(a132);
  casadi_real a145=sin(a137);
  a141=(a145*a141);
  casadi_real a146=(a144*a141);
  a143=(a143-a146);
  a107=(a62*a107);
  a107=(a107+a65);
  a146=(a104*a107);
  a146=(a17+a146);
  casadi_real a147=(a16*a146);
  a147=(a147+a21);
  a109=(a62*a109);
  a109=(a109+a20);
  a21=(a104*a109);
  a21=(a23+a21);
  casadi_real a148=(a22*a21);
  a148=(a148+a26);
  a26=(a133*a148);
  a112=(a62*a112);
  a112=(a112+a73);
  casadi_real a149=(a104*a112);
  a149=(a28+a149);
  casadi_real a150=(a22*a149);
  a150=(a150+a31);
  a31=(a144*a150);
  a26=(a26-a31);
  a26=(a147+a26);
  a116=(a62*a116);
  a116=(a116+a115);
  a31=(a13*a116);
  a31=(a76+a31);
  casadi_real a151=(a16*a31);
  a151=(a151+a19);
  casadi_real a152=(a104*a151);
  a152=(a33+a152);
  casadi_real a153=sin(a132);
  casadi_real a154=(a104*a110);
  a154=(a35+a154);
  casadi_real a155=(a153*a154);
  a132=cos(a132);
  casadi_real a156=(a104*a113);
  a156=(a38+a156);
  casadi_real a157=(a132*a156);
  a155=(a155+a157);
  a155=(a152*a155);
  a155=(a32*a155);
  a26=(a26-a155);
  a143=(a143*a26);
  a142=(a153*a142);
  a141=(a132*a141);
  a142=(a142+a141);
  a102=(a62*a102);
  a102=(a102+a30);
  a141=(a104*a102);
  a141=(a11+a141);
  a155=(a16*a141);
  a155=(a155+a39);
  a39=(a153*a148);
  a157=(a132*a150);
  a39=(a39+a157);
  a39=(a155+a39);
  a157=(a133*a154);
  casadi_real a158=(a144*a156);
  a157=(a157-a158);
  a157=(a152*a157);
  a157=(a32*a157);
  a39=(a39+a157);
  a142=(a142*a39);
  a143=(a143+a142);
  a142=sin(a140);
  a142=(a142*a41);
  a143=(a143-a142);
  a142=sin(a137);
  a157=(a13*a124);
  a157=(a86+a157);
  a158=(a104*a157);
  a158=(a43+a158);
  casadi_real a159=sin(a158);
  casadi_real a160=(a142*a159);
  casadi_real a161=sin(a140);
  a138=(a138*a161);
  casadi_real a162=cos(a158);
  casadi_real a163=(a138*a162);
  a160=(a160+a163);
  a163=(a12*a160);
  a143=(a143+a163);
  a131=(a131+a143);
  a3=(a3+a131);
  a3=(a1*a3);
  a3=(a0+a3);
  if (res[0]!=0) res[0][0]=a3;
  a48=(a32*a48);
  a0=(a0+a48);
  a49=(a32*a49);
  a0=(a0+a49);
  a0=(a0+a59);
  a0=(a1*a0);
  a5=(a5+a0);
  if (res[0]!=0) res[0][1]=a5;
  a5=arg[0] ? arg[0][2] : 0;
  a0=(a2*a5);
  a59=arg[0] ? arg[0][3] : 0;
  a49=(a4*a59);
  a0=(a0+a49);
  a49=sin(a43);
  a9=(a9*a49);
  a48=cos(a43);
  a42=(a42*a48);
  a9=(a9-a42);
  a42=(a7*a9);
  a3=cos(a8);
  a48=(a3*a48);
  a15=(a15*a46);
  a46=(a15*a49);
  a48=(a48+a46);
  a46=(a14*a48);
  a42=(a42-a46);
  a42=(a42*a27);
  a9=(a34*a9);
  a48=(a37*a48);
  a9=(a9+a48);
  a9=(a9*a40);
  a42=(a42+a9);
  a9=cos(a10);
  a49=(a9*a49);
  a49=(a49*a41);
  a42=(a42+a49);
  a15=(a15*a47);
  a3=(a3*a44);
  a15=(a15-a3);
  a3=(a12*a15);
  a42=(a42+a3);
  a0=(a0+a42);
  a42=(a13*a0);
  a42=(a5+a42);
  a3=(a2*a42);
  a44=(a13*a5);
  a44=(a59+a44);
  a44=(a4*a44);
  a3=(a3+a44);
  a44=sin(a87);
  a54=(a54*a44);
  a87=cos(a87);
  a58=(a58*a87);
  a54=(a54-a58);
  a58=(a51*a54);
  a53=cos(a53);
  a87=(a53*a87);
  a61=(a61*a90);
  a90=(a61*a44);
  a87=(a87+a90);
  a90=(a60*a87);
  a58=(a58-a90);
  a58=(a58*a71);
  a54=(a80*a54);
  a87=(a50*a87);
  a54=(a54+a87);
  a54=(a54*a85);
  a58=(a58+a54);
  a56=cos(a56);
  a44=(a56*a44);
  a44=(a44*a41);
  a58=(a58+a44);
  a61=(a61*a91);
  a53=(a53*a88);
  a61=(a61-a53);
  a53=(a12*a61);
  a58=(a58+a53);
  a3=(a3+a58);
  a58=(a32*a3);
  a0=(a0+a58);
  a3=(a13*a3);
  a3=(a5+a3);
  a58=(a2*a3);
  a53=(a13*a42);
  a53=(a59+a53);
  a53=(a4*a53);
  a58=(a58+a53);
  a53=sin(a126);
  a98=(a98*a53);
  a126=cos(a126);
  a103=(a103*a126);
  a98=(a98-a103);
  a103=(a93*a98);
  a97=cos(a97);
  a126=(a97*a126);
  a106=(a106*a129);
  a129=(a106*a53);
  a126=(a126+a129);
  a129=(a105*a126);
  a103=(a103-a129);
  a103=(a103*a111);
  a98=(a119*a98);
  a126=(a92*a126);
  a98=(a98+a126);
  a98=(a98*a123);
  a103=(a103+a98);
  a101=cos(a101);
  a53=(a101*a53);
  a53=(a53*a41);
  a103=(a103+a53);
  a106=(a106*a130);
  a97=(a97*a127);
  a106=(a106-a97);
  a97=(a12*a106);
  a103=(a103+a97);
  a58=(a58+a103);
  a103=(a32*a58);
  a0=(a0+a103);
  a58=(a104*a58);
  a58=(a5+a58);
  a103=(a2*a58);
  a97=(a104*a3);
  a97=(a59+a97);
  a97=(a4*a97);
  a103=(a103+a97);
  a97=sin(a158);
  a138=(a138*a97);
  a158=cos(a158);
  a142=(a142*a158);
  a138=(a138-a142);
  a142=(a133*a138);
  a137=cos(a137);
  a158=(a137*a158);
  a145=(a145*a161);
  a161=(a145*a97);
  a158=(a158+a161);
  a161=(a144*a158);
  a142=(a142-a161);
  a142=(a142*a26);
  a138=(a153*a138);
  a158=(a132*a158);
  a138=(a138+a158);
  a138=(a138*a39);
  a142=(a142+a138);
  a140=cos(a140);
  a97=(a140*a97);
  a97=(a97*a41);
  a142=(a142+a97);
  a145=(a145*a162);
  a137=(a137*a159);
  a145=(a145-a137);
  a12=(a12*a145);
  a142=(a142+a12);
  a103=(a103+a142);
  a0=(a0+a103);
  a0=(a1*a0);
  a0=(a5+a0);
  if (res[0]!=0) res[0][2]=a0;
  a42=(a32*a42);
  a5=(a5+a42);
  a3=(a32*a3);
  a5=(a5+a3);
  a5=(a5+a58);
  a5=(a1*a5);
  a59=(a59+a5);
  if (res[0]!=0) res[0][3]=a59;
  a59=arg[0] ? arg[0][4] : 0;
  a5=(a2*a59);
  a58=arg[0] ? arg[0][5] : 0;
  a3=(a4*a58);
  a5=(a5+a3);
  a7=(a7*a45);
  a14=(a14*a15);
  a7=(a7-a14);
  a7=(a7*a27);
  a34=(a34*a45);
  a37=(a37*a15);
  a34=(a34+a37);
  a34=(a34*a40);
  a7=(a7+a34);
  a9=(a9*a47);
  a9=(a9*a41);
  a7=(a7+a9);
  a5=(a5+a7);
  a7=(a13*a5);
  a7=(a59+a7);
  a9=(a2*a7);
  a47=(a13*a59);
  a47=(a58+a47);
  a47=(a4*a47);
  a9=(a9+a47);
  a51=(a51*a89);
  a60=(a60*a61);
  a51=(a51-a60);
  a51=(a51*a71);
  a80=(a80*a89);
  a50=(a50*a61);
  a80=(a80+a50);
  a80=(a80*a85);
  a51=(a51+a80);
  a56=(a56*a91);
  a56=(a56*a41);
  a51=(a51+a56);
  a9=(a9+a51);
  a51=(a32*a9);
  a5=(a5+a51);
  a9=(a13*a9);
  a9=(a59+a9);
  a51=(a2*a9);
  a56=(a13*a7);
  a56=(a58+a56);
  a56=(a4*a56);
  a51=(a51+a56);
  a93=(a93*a128);
  a105=(a105*a106);
  a93=(a93-a105);
  a93=(a93*a111);
  a119=(a119*a128);
  a92=(a92*a106);
  a119=(a119+a92);
  a119=(a119*a123);
  a93=(a93+a119);
  a101=(a101*a130);
  a101=(a101*a41);
  a93=(a93+a101);
  a51=(a51+a93);
  a93=(a32*a51);
  a5=(a5+a93);
  a51=(a104*a51);
  a51=(a59+a51);
  a2=(a2*a51);
  a93=(a104*a9);
  a93=(a58+a93);
  a4=(a4*a93);
  a2=(a2+a4);
  a133=(a133*a160);
  a144=(a144*a145);
  a133=(a133-a144);
  a133=(a133*a26);
  a153=(a153*a160);
  a132=(a132*a145);
  a153=(a153+a132);
  a153=(a153*a39);
  a133=(a133+a153);
  a140=(a140*a162);
  a140=(a140*a41);
  a133=(a133+a140);
  a2=(a2+a133);
  a5=(a5+a2);
  a5=(a1*a5);
  a5=(a59+a5);
  if (res[0]!=0) res[0][4]=a5;
  a7=(a32*a7);
  a59=(a59+a7);
  a9=(a32*a9);
  a59=(a59+a9);
  a59=(a59+a51);
  a59=(a1*a59);
  a58=(a58+a59);
  if (res[0]!=0) res[0][5]=a58;
  a58=arg[0] ? arg[0][6] : 0;
  a59=-1.8702006980802791e-01;
  a51=(a59*a58);
  a9=-2.1815008726003490e-03;
  a7=arg[0] ? arg[0][7] : 0;
  a5=(a9*a7);
  a51=(a51+a5);
  a51=(a51+a86);
  a5=(a13*a51);
  a5=(a58+a5);
  a2=(a59*a5);
  a133=(a13*a58);
  a133=(a7+a133);
  a133=(a9*a133);
  a2=(a2+a133);
  a2=(a2+a125);
  a133=(a32*a2);
  a51=(a51+a133);
  a2=(a13*a2);
  a2=(a58+a2);
  a133=(a59*a2);
  a140=(a13*a5);
  a140=(a7+a140);
  a140=(a9*a140);
  a133=(a133+a140);
  a133=(a133+a157);
  a140=(a32*a133);
  a51=(a51+a140);
  a133=(a104*a133);
  a133=(a58+a133);
  a140=(a59*a133);
  a162=(a104*a2);
  a162=(a7+a162);
  a162=(a9*a162);
  a140=(a140+a162);
  a162=(a104*a124);
  a162=(a86+a162);
  a140=(a140+a162);
  a51=(a51+a140);
  a51=(a1*a51);
  a51=(a58+a51);
  if (res[0]!=0) res[0][6]=a51;
  a5=(a32*a5);
  a58=(a58+a5);
  a2=(a32*a2);
  a58=(a58+a2);
  a58=(a58+a133);
  a58=(a1*a58);
  a7=(a7+a58);
  if (res[0]!=0) res[0][7]=a7;
  a7=arg[0] ? arg[0][8] : 0;
  a58=(a59*a7);
  a133=arg[0] ? arg[0][9] : 0;
  a2=(a9*a133);
  a58=(a58+a2);
  a58=(a58+a55);
  a2=(a13*a58);
  a2=(a7+a2);
  a5=(a59*a2);
  a51=(a13*a7);
  a51=(a133+a51);
  a51=(a9*a51);
  a5=(a5+a51);
  a5=(a5+a100);
  a51=(a32*a5);
  a58=(a58+a51);
  a5=(a13*a5);
  a5=(a7+a5);
  a51=(a59*a5);
  a140=(a13*a2);
  a140=(a133+a140);
  a140=(a9*a140);
  a51=(a51+a140);
  a51=(a51+a139);
  a140=(a32*a51);
  a58=(a58+a140);
  a51=(a104*a51);
  a51=(a7+a51);
  a140=(a59*a51);
  a153=(a104*a5);
  a153=(a133+a153);
  a153=(a9*a153);
  a140=(a140+a153);
  a153=(a104*a99);
  a153=(a55+a153);
  a140=(a140+a153);
  a58=(a58+a140);
  a58=(a1*a58);
  a58=(a7+a58);
  if (res[0]!=0) res[0][8]=a58;
  a2=(a32*a2);
  a7=(a7+a2);
  a5=(a32*a5);
  a7=(a7+a5);
  a7=(a7+a51);
  a7=(a1*a7);
  a133=(a133+a7);
  if (res[0]!=0) res[0][9]=a133;
  a133=arg[0] ? arg[0][10] : 0;
  a7=(a59*a133);
  a51=arg[0] ? arg[0][11] : 0;
  a5=(a9*a51);
  a7=(a7+a5);
  a5=(a33+a52);
  a7=(a7+a5);
  a5=(a13*a7);
  a5=(a133+a5);
  a2=(a59*a5);
  a58=(a13*a133);
  a58=(a51+a58);
  a58=(a9*a58);
  a2=(a2+a58);
  a58=(a79+a96);
  a2=(a2+a58);
  a58=(a32*a2);
  a7=(a7+a58);
  a2=(a13*a2);
  a2=(a133+a2);
  a58=(a59*a2);
  a140=(a13*a5);
  a140=(a51+a140);
  a140=(a9*a140);
  a58=(a58+a140);
  a140=(a118+a136);
  a58=(a58+a140);
  a140=(a32*a58);
  a7=(a7+a140);
  a58=(a104*a58);
  a58=(a133+a58);
  a59=(a59*a58);
  a140=(a104*a2);
  a140=(a51+a140);
  a9=(a9*a140);
  a59=(a59+a9);
  a78=(a62*a78);
  a78=(a78+a64);
  a9=(a13*a78);
  a9=(a94+a9);
  a140=(a22*a9);
  a140=(a140+a25);
  a39=(a104*a140);
  a39=(a52+a39);
  a132=(a152+a39);
  a59=(a59+a132);
  a7=(a7+a59);
  a7=(a1*a7);
  a7=(a133+a7);
  if (res[0]!=0) res[0][10]=a7;
  a5=(a32*a5);
  a133=(a133+a5);
  a2=(a32*a2);
  a133=(a133+a2);
  a133=(a133+a58);
  a133=(a1*a133);
  a51=(a51+a133);
  if (res[0]!=0) res[0][11]=a51;
  a51=arg[0] ? arg[0][12] : 0;
  a81=(a32*a81);
  a81=(a35+a81);
  a120=(a32*a120);
  a81=(a81+a120);
  a81=(a81+a154);
  a81=(a1*a81);
  a51=(a51+a81);
  if (res[0]!=0) res[0][12]=a51;
  a51=arg[0] ? arg[0][13] : 0;
  a83=(a32*a83);
  a83=(a38+a83);
  a122=(a32*a122);
  a83=(a83+a122);
  a83=(a83+a156);
  a83=(a1*a83);
  a51=(a51+a83);
  if (res[0]!=0) res[0][13]=a51;
  a51=arg[0] ? arg[0][14] : 0;
  a83=arg[0] ? arg[0][17] : 0;
  a156=(a13*a41);
  a156=(a83+a156);
  a156=(a32*a156);
  a156=(a83+a156);
  a122=(a13*a41);
  a122=(a83+a122);
  a122=(a32*a122);
  a156=(a156+a122);
  a122=(a104*a41);
  a122=(a83+a122);
  a156=(a156+a122);
  a156=(a1*a156);
  a51=(a51+a156);
  if (res[0]!=0) res[0][14]=a51;
  a70=(a32*a70);
  a24=(a24+a70);
  a110=(a32*a110);
  a24=(a24+a110);
  a24=(a24+a148);
  a24=(a1*a24);
  a35=(a35+a24);
  if (res[0]!=0) res[0][15]=a35;
  a75=(a32*a75);
  a29=(a29+a75);
  a113=(a32*a113);
  a29=(a29+a113);
  a29=(a29+a150);
  a29=(a1*a29);
  a38=(a38+a29);
  if (res[0]!=0) res[0][16]=a38;
  a38=(a32*a41);
  a38=(a41+a38);
  a29=(a32*a41);
  a38=(a38+a29);
  a38=(a38+a41);
  a38=(a1*a38);
  a83=(a83+a38);
  if (res[0]!=0) res[0][17]=a83;
  a83=arg[0] ? arg[0][18] : 0;
  a38=arg[0] ? arg[0][20] : 0;
  a41=(a13*a18);
  a41=(a38+a41);
  a41=(a32*a41);
  a41=(a38+a41);
  a29=(a13*a67);
  a29=(a38+a29);
  a29=(a32*a29);
  a41=(a41+a29);
  a29=(a104*a108);
  a29=(a38+a29);
  a41=(a41+a29);
  a41=(a1*a41);
  a83=(a83+a41);
  if (res[0]!=0) res[0][18]=a83;
  a83=arg[0] ? arg[0][19] : 0;
  a41=arg[0] ? arg[0][21] : 0;
  a29=(a13*a36);
  a29=(a41+a29);
  a29=(a32*a29);
  a29=(a41+a29);
  a13=(a13*a84);
  a13=(a41+a13);
  a13=(a32*a13);
  a29=(a29+a13);
  a13=(a104*a121);
  a13=(a41+a13);
  a29=(a29+a13);
  a29=(a1*a29);
  a83=(a83+a29);
  if (res[0]!=0) res[0][19]=a83;
  a67=(a32*a67);
  a18=(a18+a67);
  a108=(a32*a108);
  a18=(a18+a108);
  a18=(a18+a147);
  a18=(a1*a18);
  a38=(a38+a18);
  if (res[0]!=0) res[0][20]=a38;
  a84=(a32*a84);
  a36=(a36+a84);
  a121=(a32*a121);
  a36=(a36+a121);
  a36=(a36+a155);
  a36=(a1*a36);
  a41=(a41+a36);
  if (res[0]!=0) res[0][21]=a41;
  a96=(a32*a96);
  a96=(a52+a96);
  a136=(a32*a136);
  a96=(a96+a136);
  a96=(a96+a39);
  a96=(a1*a96);
  a8=(a8+a96);
  if (res[0]!=0) res[0][22]=a8;
  a135=(a32*a135);
  a95=(a95+a135);
  a140=(a32*a140);
  a95=(a95+a140);
  a9=(a62*a9);
  a9=(a9+a64);
  a140=(a104*a9);
  a140=(a94+a140);
  a22=(a22*a140);
  a22=(a22+a25);
  a95=(a95+a22);
  a95=(a1*a95);
  a52=(a52+a95);
  if (res[0]!=0) res[0][23]=a52;
  a100=(a32*a100);
  a100=(a55+a100);
  a139=(a32*a139);
  a100=(a100+a139);
  a100=(a100+a153);
  a100=(a1*a100);
  a10=(a10+a100);
  if (res[0]!=0) res[0][24]=a10;
  a10=(a32*a99);
  a10=(a99+a10);
  a100=(a32*a99);
  a10=(a10+a100);
  a10=(a10+a99);
  a10=(a1*a10);
  a55=(a55+a10);
  if (res[0]!=0) res[0][25]=a55;
  a125=(a32*a125);
  a125=(a86+a125);
  a157=(a32*a157);
  a125=(a125+a157);
  a125=(a125+a162);
  a125=(a1*a125);
  a43=(a43+a125);
  if (res[0]!=0) res[0][26]=a43;
  a43=(a32*a124);
  a43=(a124+a43);
  a125=(a32*a124);
  a43=(a43+a125);
  a43=(a43+a124);
  a43=(a1*a43);
  a86=(a86+a43);
  if (res[0]!=0) res[0][27]=a86;
  a79=(a32*a79);
  a79=(a33+a79);
  a118=(a32*a118);
  a79=(a79+a118);
  a79=(a79+a152);
  a79=(a1*a79);
  a6=(a6+a79);
  if (res[0]!=0) res[0][28]=a6;
  a117=(a32*a117);
  a77=(a77+a117);
  a151=(a32*a151);
  a77=(a77+a151);
  a31=(a62*a31);
  a31=(a31+a115);
  a104=(a104*a31);
  a104=(a76+a104);
  a16=(a16*a104);
  a16=(a16+a19);
  a77=(a77+a16);
  a77=(a1*a77);
  a33=(a33+a77);
  if (res[0]!=0) res[0][29]=a33;
  a69=(a32*a69);
  a68=(a68+a69);
  a109=(a32*a109);
  a68=(a68+a109);
  a21=(a62*a21);
  a21=(a21+a20);
  a68=(a68+a21);
  a68=(a1*a68);
  a23=(a23+a68);
  if (res[0]!=0) res[0][30]=a23;
  a74=(a32*a74);
  a72=(a72+a74);
  a112=(a32*a112);
  a72=(a72+a112);
  a149=(a62*a149);
  a149=(a149+a73);
  a72=(a72+a149);
  a72=(a1*a72);
  a28=(a28+a72);
  if (res[0]!=0) res[0][31]=a28;
  a66=(a32*a66);
  a63=(a63+a66);
  a107=(a32*a107);
  a63=(a63+a107);
  a146=(a62*a146);
  a146=(a146+a65);
  a63=(a63+a146);
  a63=(a1*a63);
  a17=(a17+a63);
  if (res[0]!=0) res[0][32]=a17;
  a82=(a32*a82);
  a57=(a57+a82);
  a102=(a32*a102);
  a57=(a57+a102);
  a141=(a62*a141);
  a141=(a141+a30);
  a57=(a57+a141);
  a57=(a1*a57);
  a11=(a11+a57);
  if (res[0]!=0) res[0][33]=a11;
  a78=(a32*a78);
  a134=(a134+a78);
  a9=(a32*a9);
  a134=(a134+a9);
  a140=(a62*a140);
  a140=(a140+a64);
  a134=(a134+a140);
  a134=(a1*a134);
  a94=(a94+a134);
  if (res[0]!=0) res[0][34]=a94;
  a116=(a32*a116);
  a114=(a114+a116);
  a32=(a32*a31);
  a114=(a114+a32);
  a62=(a62*a104);
  a62=(a62+a115);
  a114=(a114+a62);
  a1=(a1*a114);
  a76=(a76+a1);
  if (res[0]!=0) res[0][35]=a76;
  return 0;
}

CASADI_SYMBOL_EXPORT int Simulate_system(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void Simulate_system_incref(void) {
}

CASADI_SYMBOL_EXPORT void Simulate_system_decref(void) {
}

CASADI_SYMBOL_EXPORT int Simulate_system_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int Simulate_system_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* Simulate_system_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Simulate_system_name_out(int i){
  switch (i) {
    case 0: return "xf";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Simulate_system_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Simulate_system_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Simulate_system_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 164;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_Simulate_system(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  int i, j;
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"Simulate_system\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"Simulate_system\" failed. Too many output arguments (%d, max 1)", resc);
  int *iw = 0;
  casadi_real w[242];
  const casadi_real* arg[3] = {0};
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+78);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+36, casadi_s1, w+78);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+42, casadi_s2, w+78);
  casadi_real* res[1] = {0};
  --resc;
  res[0] = w+42;
  i = Simulate_system(arg, res, iw, w+78, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"Simulate_system\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s0, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[16];
  int buf_ok = --argc >= 0 && !mxGetString(*argv++, buf, sizeof(buf));
  if (!buf_ok) {
    /* name error */
  } else if (strcmp(buf, "Simulate_system")==0) {
    return mex_Simulate_system(resc, resv, argc, argv);
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'Simulate_system'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
