/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_src_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f15 CASADI_PREFIX(f15)
#define casadi_f16 CASADI_PREFIX(f16)
#define casadi_f17 CASADI_PREFIX(f17)
#define casadi_f18 CASADI_PREFIX(f18)
#define casadi_f19 CASADI_PREFIX(f19)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f20 CASADI_PREFIX(f20)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Printing routine */
#define PRINTF printf

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const int casadi_s1[5] = {1, 1, 0, 1, 0};
static const int casadi_s2[7] = {3, 1, 0, 3, 0, 1, 2};
static const int casadi_s3[33] = {5, 5, 0, 5, 10, 15, 20, 25, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const int casadi_s4[6] = {2, 1, 0, 2, 0, 1};
static const int casadi_s5[3] = {0, 0, 0};
static const int casadi_s6[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const int casadi_s7[18] = {2, 5, 0, 2, 4, 6, 8, 10, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1};
static const int casadi_s8[13] = {1, 5, 0, 1, 2, 3, 4, 5, 0, 0, 0, 0, 0};
static const int casadi_s9[8] = {0, 5, 0, 0, 0, 0, 0, 0};
static const int casadi_s10[4] = {0, 1, 0, 0};
static const int casadi_s11[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

/* f_fun:(states[5],controls,params[3])->(xdot[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=arg[2] ? arg[2][2] : 0;
  casadi_real a2=200.;
  casadi_real a3=10.;
  casadi_real a4=arg[0] ? arg[0][0] : 0;
  casadi_real a5=(a3*a4);
  a5=sq(a5);
  a2=(a2*a5);
  a5=2000.;
  a2=(a2+a5);
  a5=67.;
  a2=(a2/a5);
  a2=(a2*a0);
  casadi_real a6=12000.;
  a3=(a3*a4);
  a3=sq(a3);
  a6=(a6*a3);
  a3=1000.;
  a6=(a6+a3);
  a6=(a6*a4);
  a6=(a6/a5);
  a2=(a2+a6);
  a1=(a1-a2);
  a2=9.8100000000000005e+000;
  a6=arg[2] ? arg[2][1] : 0;
  a2=(a2*a6);
  a1=(a1+a2);
  a2=10000.;
  a6=arg[0] ? arg[0][2] : 0;
  casadi_real a7=(a2*a6);
  a7=(a7/a5);
  a1=(a1-a7);
  if (res[0]!=0) res[0][1]=a1;
  a1=fabs(a0);
  a1=(a1*a6);
  a6=30.;
  a7=3.1830988618379069e-001;
  casadi_real a8=9.8480775301220802e-001;
  casadi_real a9=arg[2] ? arg[2][0] : 0;
  a5=(a5*a9);
  a8=(a8*a5);
  a5=8.5174431145629327e+001;
  a8=(a8+a5);
  a8=atan(a8);
  a7=(a7*a8);
  a8=5.9999999999999998e-001;
  a7=(a7+a8);
  a6=(a6*a7);
  a8=15.;
  a8=(a8*a7);
  a7=5.0000000000000001e-003;
  a7=(a0/a7);
  a7=sq(a7);
  a7=(-a7);
  a7=exp(a7);
  a8=(a8*a7);
  a6=(a6+a8);
  a6=(a6/a2);
  a1=(a1/a6);
  a1=(a0-a1);
  if (res[0]!=0) res[0][2]=a1;
  a1=2400000.;
  a6=sq(a4);
  a1=(a1*a6);
  a1=(a1*a0);
  a6=1200000.;
  a4=sq(a4);
  a6=(a6*a4);
  a6=(a6+a3);
  a6=(a6*a0);
  a1=(a1+a6);
  a6=arg[1] ? arg[1][0] : 0;
  a1=(a1+a6);
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void f_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int f_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int f_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* f_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_fun_name_out(int i){
  switch (i) {
    case 0: return "xdot";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* f_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* f_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 10;
  return 0;
}

/* vdeFun:(i0[5],i1,i2[3],i3[5x5],i4[5])->(o0[5x5],o1[5]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[3] ? arg[3][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=arg[0] ? arg[0][1] : 0;
  casadi_real a2=1.4925373134328358e-002;
  casadi_real a3=200.;
  casadi_real a4=10.;
  casadi_real a5=arg[0] ? arg[0][0] : 0;
  casadi_real a6=(a4*a5);
  casadi_real a7=(a6+a6);
  casadi_real a8=arg[3] ? arg[3][0] : 0;
  casadi_real a9=(a4*a8);
  a9=(a7*a9);
  a9=(a3*a9);
  a9=(a2*a9);
  a9=(a1*a9);
  casadi_real a10=sq(a6);
  a10=(a3*a10);
  casadi_real a11=2000.;
  a10=(a10+a11);
  a11=67.;
  a10=(a10/a11);
  casadi_real a12=(a10*a0);
  a9=(a9+a12);
  a12=12000.;
  casadi_real a13=(a4*a5);
  casadi_real a14=(a13+a13);
  casadi_real a15=(a4*a8);
  a15=(a14*a15);
  a15=(a12*a15);
  a15=(a5*a15);
  casadi_real a16=sq(a13);
  a16=(a12*a16);
  casadi_real a17=1000.;
  a16=(a16+a17);
  casadi_real a18=(a16*a8);
  a15=(a15+a18);
  a15=(a2*a15);
  a9=(a9+a15);
  a15=10000.;
  a18=arg[3] ? arg[3][2] : 0;
  casadi_real a19=(a15*a18);
  a19=(a2*a19);
  a9=(a9+a19);
  a9=(-a9);
  if (res[0]!=0) res[0][1]=a9;
  a9=arg[0] ? arg[0][2] : 0;
  a19=sign(a1);
  casadi_real a20=(a19*a0);
  a20=(a9*a20);
  casadi_real a21=fabs(a1);
  a18=(a21*a18);
  a20=(a20+a18);
  a18=30.;
  casadi_real a22=3.1830988618379069e-001;
  casadi_real a23=9.8480775301220802e-001;
  casadi_real a24=arg[2] ? arg[2][0] : 0;
  a11=(a11*a24);
  a23=(a23*a11);
  a11=8.5174431145629327e+001;
  a23=(a23+a11);
  a23=atan(a23);
  a22=(a22*a23);
  a23=5.9999999999999998e-001;
  a22=(a22+a23);
  a18=(a18*a22);
  a23=15.;
  a23=(a23*a22);
  a22=5.0000000000000001e-003;
  a22=(a1/a22);
  a11=sq(a22);
  a11=(-a11);
  a11=exp(a11);
  a24=(a23*a11);
  a18=(a18+a24);
  a18=(a18/a15);
  a20=(a20/a18);
  a24=(a21*a9);
  a24=(a24/a18);
  casadi_real a25=(a24/a18);
  casadi_real a26=1.0000000000000000e-004;
  casadi_real a27=(a22+a22);
  casadi_real a28=(a3*a0);
  a28=(a27*a28);
  a28=(a11*a28);
  a28=(a23*a28);
  a28=(a26*a28);
  a28=(a25*a28);
  a20=(a20+a28);
  a20=(a0-a20);
  if (res[0]!=0) res[0][2]=a20;
  a20=2400000.;
  a28=(a5+a5);
  casadi_real a29=(a28*a8);
  a29=(a20*a29);
  a29=(a1*a29);
  casadi_real a30=sq(a5);
  a30=(a20*a30);
  casadi_real a31=(a30*a0);
  a29=(a29+a31);
  a31=1200000.;
  casadi_real a32=(a5+a5);
  a8=(a32*a8);
  a8=(a31*a8);
  a8=(a1*a8);
  casadi_real a33=sq(a5);
  a33=(a31*a33);
  a33=(a33+a17);
  a0=(a33*a0);
  a8=(a8+a0);
  a29=(a29+a8);
  if (res[0]!=0) res[0][3]=a29;
  a29=0.;
  if (res[0]!=0) res[0][4]=a29;
  a8=arg[3] ? arg[3][6] : 0;
  if (res[0]!=0) res[0][5]=a8;
  a0=arg[3] ? arg[3][5] : 0;
  a17=(a4*a0);
  a17=(a7*a17);
  a17=(a3*a17);
  a17=(a2*a17);
  a17=(a1*a17);
  casadi_real a34=(a10*a8);
  a17=(a17+a34);
  a34=(a4*a0);
  a34=(a14*a34);
  a34=(a12*a34);
  a34=(a5*a34);
  casadi_real a35=(a16*a0);
  a34=(a34+a35);
  a34=(a2*a34);
  a17=(a17+a34);
  a34=arg[3] ? arg[3][7] : 0;
  a35=(a15*a34);
  a35=(a2*a35);
  a17=(a17+a35);
  a17=(-a17);
  if (res[0]!=0) res[0][6]=a17;
  a17=(a19*a8);
  a17=(a9*a17);
  a34=(a21*a34);
  a17=(a17+a34);
  a17=(a17/a18);
  a34=(a3*a8);
  a34=(a27*a34);
  a34=(a11*a34);
  a34=(a23*a34);
  a34=(a26*a34);
  a34=(a25*a34);
  a17=(a17+a34);
  a17=(a8-a17);
  if (res[0]!=0) res[0][7]=a17;
  a17=(a28*a0);
  a17=(a20*a17);
  a17=(a1*a17);
  a34=(a30*a8);
  a17=(a17+a34);
  a0=(a32*a0);
  a0=(a31*a0);
  a0=(a1*a0);
  a8=(a33*a8);
  a0=(a0+a8);
  a17=(a17+a0);
  if (res[0]!=0) res[0][8]=a17;
  if (res[0]!=0) res[0][9]=a29;
  a17=arg[3] ? arg[3][11] : 0;
  if (res[0]!=0) res[0][10]=a17;
  a0=arg[3] ? arg[3][10] : 0;
  a8=(a4*a0);
  a8=(a7*a8);
  a8=(a3*a8);
  a8=(a2*a8);
  a8=(a1*a8);
  a34=(a10*a17);
  a8=(a8+a34);
  a34=(a4*a0);
  a34=(a14*a34);
  a34=(a12*a34);
  a34=(a5*a34);
  a35=(a16*a0);
  a34=(a34+a35);
  a34=(a2*a34);
  a8=(a8+a34);
  a34=arg[3] ? arg[3][12] : 0;
  a35=(a15*a34);
  a35=(a2*a35);
  a8=(a8+a35);
  a8=(-a8);
  if (res[0]!=0) res[0][11]=a8;
  a8=(a19*a17);
  a8=(a9*a8);
  a34=(a21*a34);
  a8=(a8+a34);
  a8=(a8/a18);
  a34=(a3*a17);
  a34=(a27*a34);
  a34=(a11*a34);
  a34=(a23*a34);
  a34=(a26*a34);
  a34=(a25*a34);
  a8=(a8+a34);
  a8=(a17-a8);
  if (res[0]!=0) res[0][12]=a8;
  a8=(a28*a0);
  a8=(a20*a8);
  a8=(a1*a8);
  a34=(a30*a17);
  a8=(a8+a34);
  a0=(a32*a0);
  a0=(a31*a0);
  a0=(a1*a0);
  a17=(a33*a17);
  a0=(a0+a17);
  a8=(a8+a0);
  if (res[0]!=0) res[0][13]=a8;
  if (res[0]!=0) res[0][14]=a29;
  a8=arg[3] ? arg[3][16] : 0;
  if (res[0]!=0) res[0][15]=a8;
  a0=arg[3] ? arg[3][15] : 0;
  a17=(a4*a0);
  a17=(a7*a17);
  a17=(a3*a17);
  a17=(a2*a17);
  a17=(a1*a17);
  a34=(a10*a8);
  a17=(a17+a34);
  a34=(a4*a0);
  a34=(a14*a34);
  a34=(a12*a34);
  a34=(a5*a34);
  a35=(a16*a0);
  a34=(a34+a35);
  a34=(a2*a34);
  a17=(a17+a34);
  a34=arg[3] ? arg[3][17] : 0;
  a35=(a15*a34);
  a35=(a2*a35);
  a17=(a17+a35);
  a17=(-a17);
  if (res[0]!=0) res[0][16]=a17;
  a17=(a19*a8);
  a17=(a9*a17);
  a34=(a21*a34);
  a17=(a17+a34);
  a17=(a17/a18);
  a34=(a3*a8);
  a34=(a27*a34);
  a34=(a11*a34);
  a34=(a23*a34);
  a34=(a26*a34);
  a34=(a25*a34);
  a17=(a17+a34);
  a17=(a8-a17);
  if (res[0]!=0) res[0][17]=a17;
  a17=(a28*a0);
  a17=(a20*a17);
  a17=(a1*a17);
  a34=(a30*a8);
  a17=(a17+a34);
  a0=(a32*a0);
  a0=(a31*a0);
  a0=(a1*a0);
  a8=(a33*a8);
  a0=(a0+a8);
  a17=(a17+a0);
  if (res[0]!=0) res[0][18]=a17;
  if (res[0]!=0) res[0][19]=a29;
  a17=arg[3] ? arg[3][21] : 0;
  if (res[0]!=0) res[0][20]=a17;
  a0=arg[3] ? arg[3][20] : 0;
  a8=(a4*a0);
  a7=(a7*a8);
  a7=(a3*a7);
  a7=(a2*a7);
  a7=(a1*a7);
  a8=(a10*a17);
  a7=(a7+a8);
  a8=(a4*a0);
  a14=(a14*a8);
  a14=(a12*a14);
  a14=(a5*a14);
  a8=(a16*a0);
  a14=(a14+a8);
  a14=(a2*a14);
  a7=(a7+a14);
  a14=arg[3] ? arg[3][22] : 0;
  a8=(a15*a14);
  a8=(a2*a8);
  a7=(a7+a8);
  a7=(-a7);
  if (res[0]!=0) res[0][21]=a7;
  a19=(a19*a17);
  a19=(a9*a19);
  a14=(a21*a14);
  a19=(a19+a14);
  a19=(a19/a18);
  a14=(a3*a17);
  a27=(a27*a14);
  a27=(a11*a27);
  a27=(a23*a27);
  a27=(a26*a27);
  a25=(a25*a27);
  a19=(a19+a25);
  a19=(a17-a19);
  if (res[0]!=0) res[0][22]=a19;
  a28=(a28*a0);
  a28=(a20*a28);
  a28=(a1*a28);
  a19=(a30*a17);
  a28=(a28+a19);
  a32=(a32*a0);
  a32=(a31*a32);
  a32=(a1*a32);
  a17=(a33*a17);
  a32=(a32+a17);
  a28=(a28+a32);
  if (res[0]!=0) res[0][23]=a28;
  if (res[0]!=0) res[0][24]=a29;
  a29=arg[4] ? arg[4][1] : 0;
  if (res[1]!=0) res[1][0]=a29;
  a6=(a6+a6);
  a28=arg[4] ? arg[4][0] : 0;
  a32=(a4*a28);
  a6=(a6*a32);
  a6=(a3*a6);
  a6=(a2*a6);
  a6=(a1*a6);
  a10=(a10*a29);
  a6=(a6+a10);
  a13=(a13+a13);
  a4=(a4*a28);
  a13=(a13*a4);
  a12=(a12*a13);
  a12=(a5*a12);
  a16=(a16*a28);
  a12=(a12+a16);
  a12=(a2*a12);
  a6=(a6+a12);
  a12=arg[4] ? arg[4][2] : 0;
  a15=(a15*a12);
  a2=(a2*a15);
  a6=(a6+a2);
  a6=(-a6);
  if (res[1]!=0) res[1][1]=a6;
  a6=sign(a1);
  a6=(a6*a29);
  a9=(a9*a6);
  a21=(a21*a12);
  a9=(a9+a21);
  a9=(a9/a18);
  a24=(a24/a18);
  a22=(a22+a22);
  a3=(a3*a29);
  a22=(a22*a3);
  a11=(a11*a22);
  a23=(a23*a11);
  a26=(a26*a23);
  a24=(a24*a26);
  a9=(a9+a24);
  a9=(a29-a9);
  if (res[1]!=0) res[1][2]=a9;
  a9=1.;
  a24=(a5+a5);
  a24=(a24*a28);
  a20=(a20*a24);
  a20=(a1*a20);
  a30=(a30*a29);
  a20=(a20+a30);
  a5=(a5+a5);
  a5=(a5*a28);
  a31=(a31*a5);
  a1=(a1*a31);
  a33=(a33*a29);
  a1=(a1+a33);
  a20=(a20+a1);
  a20=(a9+a20);
  if (res[1]!=0) res[1][3]=a20;
  if (res[1]!=0) res[1][4]=a9;
  return 0;
}

CASADI_SYMBOL_EXPORT int vdeFun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void vdeFun_incref(void) {
}

CASADI_SYMBOL_EXPORT void vdeFun_decref(void) {
}

CASADI_SYMBOL_EXPORT int vdeFun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int vdeFun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* vdeFun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* vdeFun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* vdeFun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* vdeFun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int vdeFun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 36;
  return 0;
}

/* impl_f_fun:(i0[5],i1,i2[3],i3[5])->(o0[5]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[3] ? arg[3][0] : 0;
  casadi_real a1=arg[0] ? arg[0][1] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[3] ? arg[3][1] : 0;
  casadi_real a2=arg[2] ? arg[2][2] : 0;
  casadi_real a3=200.;
  casadi_real a4=10.;
  casadi_real a5=arg[0] ? arg[0][0] : 0;
  casadi_real a6=(a4*a5);
  a6=sq(a6);
  a3=(a3*a6);
  a6=2000.;
  a3=(a3+a6);
  a6=67.;
  a3=(a3/a6);
  a3=(a3*a1);
  casadi_real a7=12000.;
  a4=(a4*a5);
  a4=sq(a4);
  a7=(a7*a4);
  a4=1000.;
  a7=(a7+a4);
  a7=(a7*a5);
  a7=(a7/a6);
  a3=(a3+a7);
  a2=(a2-a3);
  a3=9.8100000000000005e+000;
  a7=arg[2] ? arg[2][1] : 0;
  a3=(a3*a7);
  a2=(a2+a3);
  a3=10000.;
  a7=arg[0] ? arg[0][2] : 0;
  casadi_real a8=(a3*a7);
  a8=(a8/a6);
  a2=(a2-a8);
  a0=(a0-a2);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[3] ? arg[3][2] : 0;
  a2=fabs(a1);
  a2=(a2*a7);
  a7=30.;
  a8=3.1830988618379069e-001;
  casadi_real a9=9.8480775301220802e-001;
  casadi_real a10=arg[2] ? arg[2][0] : 0;
  a6=(a6*a10);
  a9=(a9*a6);
  a6=8.5174431145629327e+001;
  a9=(a9+a6);
  a9=atan(a9);
  a8=(a8*a9);
  a9=5.9999999999999998e-001;
  a8=(a8+a9);
  a7=(a7*a8);
  a9=15.;
  a9=(a9*a8);
  a8=5.0000000000000001e-003;
  a8=(a1/a8);
  a8=sq(a8);
  a8=(-a8);
  a8=exp(a8);
  a9=(a9*a8);
  a7=(a7+a9);
  a7=(a7/a3);
  a2=(a2/a7);
  a2=(a1-a2);
  a0=(a0-a2);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[3] ? arg[3][3] : 0;
  a2=2400000.;
  a7=sq(a5);
  a2=(a2*a7);
  a2=(a2*a1);
  a7=1200000.;
  a5=sq(a5);
  a7=(a7*a5);
  a7=(a7+a4);
  a7=(a7*a1);
  a2=(a2+a7);
  a7=arg[1] ? arg[1][0] : 0;
  a2=(a2+a7);
  a0=(a0-a2);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[3] ? arg[3][4] : 0;
  a0=(a0-a7);
  if (res[0]!=0) res[0][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_f_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_f_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_f_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_f_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int impl_f_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_f_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_f_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_f_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_f_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_f_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 11;
  return 0;
}

/* impl_jac_x_fun:(i0[5],i1,i2[3],i3[5])->(o0[5x5]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=arg[0] ? arg[0][1] : 0;
  casadi_real a2=1.4925373134328358e-002;
  casadi_real a3=200.;
  casadi_real a4=10.;
  casadi_real a5=arg[0] ? arg[0][0] : 0;
  casadi_real a6=(a4*a5);
  casadi_real a7=(a6+a6);
  a7=(a4*a7);
  a7=(a3*a7);
  a7=(a2*a7);
  a7=(a1*a7);
  casadi_real a8=12000.;
  casadi_real a9=(a4*a5);
  casadi_real a10=(a9+a9);
  a4=(a4*a10);
  a4=(a8*a4);
  a4=(a5*a4);
  a9=sq(a9);
  a8=(a8*a9);
  a9=1000.;
  a8=(a8+a9);
  a4=(a4+a8);
  a2=(a2*a4);
  a7=(a7+a2);
  if (res[0]!=0) res[0][1]=a7;
  if (res[0]!=0) res[0][2]=a0;
  a7=2400000.;
  a2=(a5+a5);
  a2=(a7*a2);
  a2=(a1*a2);
  a4=1200000.;
  a8=(a5+a5);
  a8=(a4*a8);
  a8=(a1*a8);
  a2=(a2+a8);
  a2=(-a2);
  if (res[0]!=0) res[0][3]=a2;
  if (res[0]!=0) res[0][4]=a0;
  a2=-1.;
  if (res[0]!=0) res[0][5]=a2;
  a6=sq(a6);
  a6=(a3*a6);
  a2=2000.;
  a6=(a6+a2);
  a2=67.;
  a6=(a6/a2);
  if (res[0]!=0) res[0][6]=a6;
  a6=1.;
  a8=arg[0] ? arg[0][2] : 0;
  a10=sign(a1);
  a10=(a8*a10);
  casadi_real a11=30.;
  casadi_real a12=3.1830988618379069e-001;
  casadi_real a13=9.8480775301220802e-001;
  casadi_real a14=arg[2] ? arg[2][0] : 0;
  a2=(a2*a14);
  a13=(a13*a2);
  a2=8.5174431145629327e+001;
  a13=(a13+a2);
  a13=atan(a13);
  a12=(a12*a13);
  a13=5.9999999999999998e-001;
  a12=(a12+a13);
  a11=(a11*a12);
  a13=15.;
  a13=(a13*a12);
  a12=5.0000000000000001e-003;
  a12=(a1/a12);
  a2=sq(a12);
  a2=(-a2);
  a2=exp(a2);
  a14=(a13*a2);
  a11=(a11+a14);
  a14=10000.;
  a11=(a11/a14);
  a10=(a10/a11);
  a1=fabs(a1);
  a8=(a1*a8);
  a8=(a8/a11);
  a8=(a8/a11);
  a14=1.0000000000000000e-004;
  a12=(a12+a12);
  a3=(a3*a12);
  a2=(a2*a3);
  a13=(a13*a2);
  a14=(a14*a13);
  a8=(a8*a14);
  a10=(a10+a8);
  a6=(a6-a10);
  a6=(-a6);
  if (res[0]!=0) res[0][7]=a6;
  a6=sq(a5);
  a7=(a7*a6);
  a5=sq(a5);
  a4=(a4*a5);
  a4=(a4+a9);
  a7=(a7+a4);
  a7=(-a7);
  if (res[0]!=0) res[0][8]=a7;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  a7=1.4925373134328359e+002;
  if (res[0]!=0) res[0][11]=a7;
  a1=(a1/a11);
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a0;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a0;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a0;
  if (res[0]!=0) res[0][23]=a0;
  if (res[0]!=0) res[0][24]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_x_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_x_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_x_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_x_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int impl_jac_x_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_x_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_x_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_x_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_x_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_x_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 15;
  return 0;
}

/* impl_jac_u_fun:(i0[5],i1,i2[3],i3[5])->(o0[5]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a0=-1.;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_u_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_u_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_u_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_u_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int impl_jac_u_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_u_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_u_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_u_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_u_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_u_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}

/* impl_jac_xdot_fun:(i0[5],i1,i2[3],i3[5])->(o0[5x5]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  casadi_real a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a1;
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a1;
  if (res[0]!=0) res[0][22]=a1;
  if (res[0]!=0) res[0][23]=a1;
  if (res[0]!=0) res[0][24]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_xdot_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void impl_jac_xdot_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_xdot_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jac_xdot_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int impl_jac_xdot_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jac_xdot_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_xdot_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_xdot_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jac_xdot_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_xdot_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* F:(i0[5],i1,i2[3])->(o0[5]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][0] : 0;
  casadi_real a1=8.3333333333333339e-004;
  casadi_real a2=arg[0] ? arg[0][1] : 0;
  casadi_real a3=2.;
  casadi_real a4=2.5000000000000001e-003;
  casadi_real a5=arg[2] ? arg[2][2] : 0;
  casadi_real a6=200.;
  casadi_real a7=10.;
  casadi_real a8=(a7*a0);
  a8=sq(a8);
  a8=(a6*a8);
  casadi_real a9=2000.;
  a8=(a8+a9);
  casadi_real a10=67.;
  a8=(a8/a10);
  a8=(a8*a2);
  casadi_real a11=12000.;
  casadi_real a12=(a7*a0);
  a12=sq(a12);
  a12=(a11*a12);
  casadi_real a13=1000.;
  a12=(a12+a13);
  a12=(a12*a0);
  a12=(a12/a10);
  a8=(a8+a12);
  a8=(a5-a8);
  a12=9.8100000000000005e+000;
  casadi_real a14=arg[2] ? arg[2][1] : 0;
  a12=(a12*a14);
  a8=(a8+a12);
  a14=10000.;
  casadi_real a15=arg[0] ? arg[0][2] : 0;
  casadi_real a16=(a14*a15);
  a16=(a16/a10);
  a8=(a8-a16);
  a16=(a4*a8);
  a16=(a2+a16);
  casadi_real a17=(a3*a16);
  a17=(a2+a17);
  casadi_real a18=(a4*a2);
  a18=(a0+a18);
  casadi_real a19=(a7*a18);
  a19=sq(a19);
  a19=(a6*a19);
  a19=(a19+a9);
  a19=(a19/a10);
  a19=(a19*a16);
  casadi_real a20=(a7*a18);
  a20=sq(a20);
  a20=(a11*a20);
  a20=(a20+a13);
  a20=(a20*a18);
  a20=(a20/a10);
  a19=(a19+a20);
  a19=(a5-a19);
  a19=(a19+a12);
  a20=fabs(a2);
  a20=(a20*a15);
  casadi_real a21=30.;
  casadi_real a22=3.1830988618379069e-001;
  casadi_real a23=9.8480775301220802e-001;
  casadi_real a24=arg[2] ? arg[2][0] : 0;
  a24=(a10*a24);
  a23=(a23*a24);
  a24=8.5174431145629327e+001;
  a23=(a23+a24);
  a23=atan(a23);
  a22=(a22*a23);
  a23=5.9999999999999998e-001;
  a22=(a22+a23);
  a21=(a21*a22);
  a23=15.;
  a23=(a23*a22);
  a22=5.0000000000000001e-003;
  a24=(a2/a22);
  a24=sq(a24);
  a24=(-a24);
  a24=exp(a24);
  a24=(a23*a24);
  a24=(a21+a24);
  a24=(a24/a14);
  a20=(a20/a24);
  a20=(a2-a20);
  a24=(a4*a20);
  a24=(a15+a24);
  casadi_real a25=(a14*a24);
  a25=(a25/a10);
  a19=(a19-a25);
  a25=(a4*a19);
  a25=(a2+a25);
  casadi_real a26=(a3*a25);
  a17=(a17+a26);
  a26=(a4*a16);
  a26=(a0+a26);
  casadi_real a27=(a7*a26);
  a27=sq(a27);
  a27=(a6*a27);
  a27=(a27+a9);
  a27=(a27/a10);
  a27=(a27*a25);
  casadi_real a28=(a7*a26);
  a28=sq(a28);
  a28=(a11*a28);
  a28=(a28+a13);
  a28=(a28*a26);
  a28=(a28/a10);
  a27=(a27+a28);
  a27=(a5-a27);
  a27=(a27+a12);
  a28=fabs(a16);
  a28=(a28*a24);
  a24=(a16/a22);
  a24=sq(a24);
  a24=(-a24);
  a24=exp(a24);
  a24=(a23*a24);
  a24=(a21+a24);
  a24=(a24/a14);
  a28=(a28/a24);
  a28=(a16-a28);
  a4=(a4*a28);
  a4=(a15+a4);
  a24=(a14*a4);
  a24=(a24/a10);
  a27=(a27-a24);
  a24=(a22*a27);
  a24=(a2+a24);
  a17=(a17+a24);
  a17=(a1*a17);
  a17=(a0+a17);
  if (res[0]!=0) res[0][0]=a17;
  a19=(a3*a19);
  a8=(a8+a19);
  a27=(a3*a27);
  a8=(a8+a27);
  a27=(a22*a25);
  a27=(a0+a27);
  a19=(a7*a27);
  a19=sq(a19);
  a6=(a6*a19);
  a6=(a6+a9);
  a6=(a6/a10);
  a6=(a6*a24);
  a7=(a7*a27);
  a7=sq(a7);
  a11=(a11*a7);
  a11=(a11+a13);
  a11=(a11*a27);
  a11=(a11/a10);
  a6=(a6+a11);
  a5=(a5-a6);
  a5=(a5+a12);
  a12=fabs(a25);
  a12=(a12*a4);
  a4=(a25/a22);
  a4=sq(a4);
  a4=(-a4);
  a4=exp(a4);
  a4=(a23*a4);
  a4=(a21+a4);
  a4=(a4/a14);
  a12=(a12/a4);
  a12=(a25-a12);
  a4=(a22*a12);
  a4=(a15+a4);
  a6=(a14*a4);
  a6=(a6/a10);
  a5=(a5-a6);
  a8=(a8+a5);
  a8=(a1*a8);
  a8=(a2+a8);
  if (res[0]!=0) res[0][1]=a8;
  a28=(a3*a28);
  a20=(a20+a28);
  a12=(a3*a12);
  a20=(a20+a12);
  a12=fabs(a24);
  a12=(a12*a4);
  a22=(a24/a22);
  a22=sq(a22);
  a22=(-a22);
  a22=exp(a22);
  a23=(a23*a22);
  a21=(a21+a23);
  a21=(a21/a14);
  a12=(a12/a21);
  a12=(a24-a12);
  a20=(a20+a12);
  a20=(a1*a20);
  a15=(a15+a20);
  if (res[0]!=0) res[0][2]=a15;
  a15=arg[0] ? arg[0][3] : 0;
  a20=2400000.;
  a12=sq(a0);
  a12=(a20*a12);
  a12=(a12*a2);
  a21=1200000.;
  a0=sq(a0);
  a0=(a21*a0);
  a0=(a0+a13);
  a0=(a0*a2);
  a12=(a12+a0);
  a0=arg[1] ? arg[1][0] : 0;
  a12=(a12+a0);
  a2=sq(a18);
  a2=(a20*a2);
  a2=(a2*a16);
  a18=sq(a18);
  a18=(a21*a18);
  a18=(a18+a13);
  a18=(a18*a16);
  a2=(a2+a18);
  a2=(a2+a0);
  a2=(a3*a2);
  a12=(a12+a2);
  a2=sq(a26);
  a2=(a20*a2);
  a2=(a2*a25);
  a26=sq(a26);
  a26=(a21*a26);
  a26=(a26+a13);
  a26=(a26*a25);
  a2=(a2+a26);
  a2=(a2+a0);
  a2=(a3*a2);
  a12=(a12+a2);
  a2=sq(a27);
  a20=(a20*a2);
  a20=(a20*a24);
  a27=sq(a27);
  a21=(a21*a27);
  a21=(a21+a13);
  a21=(a21*a24);
  a20=(a20+a21);
  a20=(a20+a0);
  a12=(a12+a20);
  a12=(a1*a12);
  a15=(a15+a12);
  if (res[0]!=0) res[0][3]=a15;
  a15=arg[0] ? arg[0][4] : 0;
  a12=(a3*a0);
  a12=(a0+a12);
  a3=(a3*a0);
  a12=(a12+a3);
  a12=(a12+a0);
  a1=(a1*a12);
  a15=(a15+a1);
  if (res[0]!=0) res[0][4]=a15;
  return 0;
}

CASADI_SYMBOL_EXPORT int F(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void F_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_decref(void) {
}

CASADI_SYMBOL_EXPORT int F_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int F_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* F_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* F_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* F_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 29;
  return 0;
}

/* D:(i0[5],i1,i2[3])->(o0[5x5],o1[5]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=1.;
  casadi_real a1=8.3333333333333339e-004;
  casadi_real a2=2.;
  casadi_real a3=2.5000000000000001e-003;
  casadi_real a4=arg[0] ? arg[0][1] : 0;
  casadi_real a5=1.4925373134328358e-002;
  casadi_real a6=200.;
  casadi_real a7=10.;
  casadi_real a8=arg[0] ? arg[0][0] : 0;
  casadi_real a9=(a7*a8);
  casadi_real a10=(a9+a9);
  a10=(a7*a10);
  a10=(a6*a10);
  a10=(a5*a10);
  a10=(a4*a10);
  casadi_real a11=12000.;
  casadi_real a12=(a7*a8);
  casadi_real a13=(a12+a12);
  a13=(a7*a13);
  a13=(a11*a13);
  a13=(a8*a13);
  a12=sq(a12);
  a12=(a11*a12);
  casadi_real a14=1000.;
  a12=(a12+a14);
  a13=(a13+a12);
  a13=(a5*a13);
  a10=(a10+a13);
  a13=(a3*a10);
  casadi_real a15=(a2*a13);
  casadi_real a16=arg[2] ? arg[2][2] : 0;
  a9=sq(a9);
  a9=(a6*a9);
  casadi_real a17=2000.;
  a9=(a9+a17);
  casadi_real a18=67.;
  a9=(a9/a18);
  casadi_real a19=(a9*a4);
  a12=(a12*a8);
  a12=(a12/a18);
  a19=(a19+a12);
  a19=(a16-a19);
  a12=9.8100000000000005e+000;
  casadi_real a20=arg[2] ? arg[2][1] : 0;
  a12=(a12*a20);
  a19=(a19+a12);
  a20=10000.;
  casadi_real a21=arg[0] ? arg[0][2] : 0;
  casadi_real a22=(a20*a21);
  a22=(a22/a18);
  a19=(a19-a22);
  a19=(a3*a19);
  a19=(a4+a19);
  a22=(a3*a4);
  a22=(a8+a22);
  casadi_real a23=(a7*a22);
  casadi_real a24=(a23+a23);
  casadi_real a25=(a7*a24);
  a25=(a6*a25);
  a25=(a5*a25);
  a25=(a19*a25);
  a23=sq(a23);
  a23=(a6*a23);
  a23=(a23+a17);
  a23=(a23/a18);
  casadi_real a26=(a23*a13);
  a25=(a25-a26);
  a26=(a7*a22);
  casadi_real a27=(a26+a26);
  casadi_real a28=(a7*a27);
  a28=(a11*a28);
  a28=(a22*a28);
  a26=sq(a26);
  a26=(a11*a26);
  a26=(a26+a14);
  a28=(a28+a26);
  a28=(a5*a28);
  a25=(a25+a28);
  a28=(a3*a25);
  casadi_real a29=(a2*a28);
  a15=(a15+a29);
  a29=5.0000000000000001e-003;
  casadi_real a30=(a23*a19);
  casadi_real a31=(a26*a22);
  a31=(a31/a18);
  a30=(a30+a31);
  a30=(a16-a30);
  a30=(a30+a12);
  a31=fabs(a4);
  casadi_real a32=(a31*a21);
  casadi_real a33=30.;
  casadi_real a34=3.1830988618379069e-001;
  casadi_real a35=9.8480775301220802e-001;
  casadi_real a36=arg[2] ? arg[2][0] : 0;
  a36=(a18*a36);
  a35=(a35*a36);
  a36=8.5174431145629327e+001;
  a35=(a35+a36);
  a35=atan(a35);
  a34=(a34*a35);
  a35=5.9999999999999998e-001;
  a34=(a34+a35);
  a33=(a33*a34);
  a35=15.;
  a35=(a35*a34);
  a34=(a4/a29);
  a36=sq(a34);
  a36=(-a36);
  a36=exp(a36);
  casadi_real a37=(a35*a36);
  a37=(a33+a37);
  a37=(a37/a20);
  a32=(a32/a37);
  casadi_real a38=(a4-a32);
  a38=(a3*a38);
  a38=(a21+a38);
  casadi_real a39=(a20*a38);
  a39=(a39/a18);
  a30=(a30-a39);
  a30=(a3*a30);
  a30=(a4+a30);
  a39=(a3*a19);
  a39=(a8+a39);
  casadi_real a40=(a7*a39);
  casadi_real a41=(a40+a40);
  casadi_real a42=(a3*a13);
  a42=(a0-a42);
  casadi_real a43=(a7*a42);
  a43=(a41*a43);
  a43=(a6*a43);
  a43=(a5*a43);
  a43=(a30*a43);
  a40=sq(a40);
  a40=(a6*a40);
  a40=(a40+a17);
  a40=(a40/a18);
  casadi_real a44=(a40*a28);
  a43=(a43-a44);
  a44=(a7*a39);
  casadi_real a45=(a44+a44);
  casadi_real a46=(a7*a42);
  a46=(a45*a46);
  a46=(a11*a46);
  a46=(a39*a46);
  a44=sq(a44);
  a44=(a11*a44);
  a44=(a44+a14);
  casadi_real a47=(a44*a42);
  a46=(a46+a47);
  a46=(a5*a46);
  a43=(a43+a46);
  a46=sign(a19);
  a47=(a46*a13);
  a47=(a38*a47);
  casadi_real a48=(a19/a29);
  casadi_real a49=sq(a48);
  a49=(-a49);
  a49=exp(a49);
  casadi_real a50=(a35*a49);
  a50=(a33+a50);
  a50=(a50/a20);
  a47=(a47/a50);
  casadi_real a51=fabs(a19);
  casadi_real a52=(a51*a38);
  a52=(a52/a50);
  casadi_real a53=(a52/a50);
  casadi_real a54=1.0000000000000000e-004;
  a48=(a48+a48);
  casadi_real a55=(a6*a13);
  a55=(a48*a55);
  a55=(a49*a55);
  a55=(a35*a55);
  a55=(a54*a55);
  a55=(a53*a55);
  a47=(a47+a55);
  a47=(a47-a13);
  a55=(a3*a47);
  casadi_real a56=(a20*a55);
  a56=(a5*a56);
  a43=(a43+a56);
  a56=(a29*a43);
  a15=(a15+a56);
  a15=(a1*a15);
  a15=(a0-a15);
  if (res[0]!=0) res[0][0]=a15;
  a15=fabs(a30);
  a55=(a15*a55);
  a52=(a19-a52);
  a52=(a3*a52);
  a52=(a21+a52);
  casadi_real a57=sign(a30);
  casadi_real a58=(a57*a28);
  a58=(a52*a58);
  a55=(a55-a58);
  a58=(a30/a29);
  casadi_real a59=sq(a58);
  a59=(-a59);
  a59=exp(a59);
  casadi_real a60=(a35*a59);
  a60=(a33+a60);
  a60=(a60/a20);
  a55=(a55/a60);
  casadi_real a61=(a15*a52);
  a61=(a61/a60);
  casadi_real a62=(a61/a60);
  a58=(a58+a58);
  casadi_real a63=(a6*a28);
  a63=(a58*a63);
  a63=(a59*a63);
  a63=(a35*a63);
  a63=(a54*a63);
  a63=(a62*a63);
  a55=(a55-a63);
  a55=(a28+a55);
  a63=(a29*a55);
  casadi_real a64=(a20*a63);
  a64=(a5*a64);
  casadi_real a65=(a40*a30);
  casadi_real a66=(a44*a39);
  a66=(a66/a18);
  a65=(a65+a66);
  a16=(a16-a65);
  a16=(a16+a12);
  a12=(a20*a52);
  a12=(a12/a18);
  a16=(a16-a12);
  a16=(a29*a16);
  a16=(a4+a16);
  a12=(a29*a30);
  a12=(a8+a12);
  a65=(a7*a12);
  a66=(a65+a65);
  casadi_real a67=(a29*a28);
  a67=(a0-a67);
  casadi_real a68=(a7*a67);
  a68=(a66*a68);
  a68=(a6*a68);
  a68=(a5*a68);
  a68=(a16*a68);
  a65=sq(a65);
  a65=(a6*a65);
  a65=(a65+a17);
  a65=(a65/a18);
  a18=(a65*a56);
  a68=(a68-a18);
  a18=(a7*a12);
  a17=(a18+a18);
  casadi_real a69=(a7*a67);
  a69=(a17*a69);
  a69=(a11*a69);
  a69=(a12*a69);
  a18=sq(a18);
  a18=(a11*a18);
  a18=(a18+a14);
  casadi_real a70=(a18*a67);
  a69=(a69+a70);
  a69=(a5*a69);
  a68=(a68+a69);
  a64=(a64-a68);
  a25=(a2*a25);
  a10=(a10+a25);
  a25=(a2*a43);
  a10=(a10+a25);
  a64=(a64-a10);
  a64=(a1*a64);
  if (res[0]!=0) res[0][1]=a64;
  a47=(a2*a47);
  a55=(a2*a55);
  a47=(a47-a55);
  a61=(a30-a61);
  a61=(a29*a61);
  a61=(a21+a61);
  a55=sign(a16);
  a64=(a55*a56);
  a64=(a61*a64);
  a10=fabs(a16);
  a63=(a10*a63);
  a64=(a64+a63);
  a63=(a16/a29);
  a25=sq(a63);
  a25=(-a25);
  a25=exp(a25);
  a68=(a35*a25);
  a33=(a33+a68);
  a33=(a33/a20);
  a64=(a64/a33);
  a68=(a10*a61);
  a68=(a68/a33);
  a68=(a68/a33);
  a63=(a63+a63);
  a43=(a63*a43);
  a43=(a25*a43);
  a43=(a35*a43);
  a43=(a54*a43);
  a43=(a68*a43);
  a64=(a64+a43);
  a64=(a64-a56);
  a47=(a47+a64);
  a47=(a1*a47);
  if (res[0]!=0) res[0][2]=a47;
  a47=2400000.;
  a64=(a8+a8);
  a64=(a47*a64);
  a64=(a4*a64);
  a43=1200000.;
  a69=(a8+a8);
  a69=(a43*a69);
  a69=(a4*a69);
  a64=(a64+a69);
  a69=(a22+a22);
  a70=(a47*a69);
  a70=(a19*a70);
  casadi_real a71=sq(a22);
  a71=(a47*a71);
  casadi_real a72=(a71*a13);
  a70=(a70-a72);
  a72=(a22+a22);
  casadi_real a73=(a43*a72);
  a73=(a19*a73);
  casadi_real a74=sq(a22);
  a74=(a43*a74);
  a74=(a74+a14);
  a13=(a74*a13);
  a73=(a73-a13);
  a70=(a70+a73);
  a70=(a2*a70);
  a64=(a64+a70);
  a70=(a39+a39);
  a73=(a70*a42);
  a73=(a47*a73);
  a73=(a30*a73);
  a13=sq(a39);
  a13=(a47*a13);
  casadi_real a75=(a13*a28);
  a73=(a73-a75);
  a75=(a39+a39);
  a42=(a75*a42);
  a42=(a43*a42);
  a42=(a30*a42);
  casadi_real a76=sq(a39);
  a76=(a43*a76);
  a76=(a76+a14);
  a28=(a76*a28);
  a42=(a42-a28);
  a73=(a73+a42);
  a73=(a2*a73);
  a64=(a64+a73);
  a73=(a12+a12);
  a42=(a73*a67);
  a42=(a47*a42);
  a42=(a16*a42);
  a28=sq(a12);
  a28=(a47*a28);
  casadi_real a77=(a28*a56);
  a42=(a42-a77);
  a77=(a12+a12);
  a67=(a77*a67);
  a67=(a43*a67);
  a67=(a16*a67);
  casadi_real a78=sq(a12);
  a78=(a43*a78);
  a78=(a78+a14);
  a56=(a78*a56);
  a67=(a67-a56);
  a42=(a42+a67);
  a64=(a64+a42);
  a64=(a1*a64);
  if (res[0]!=0) res[0][3]=a64;
  a64=0.;
  if (res[0]!=0) res[0][4]=a64;
  a42=(a3*a9);
  a42=(a0-a42);
  a67=(a2*a42);
  a67=(a0+a67);
  a56=2.5000000000000001e-002;
  a24=(a56*a24);
  a24=(a6*a24);
  a24=(a5*a24);
  a24=(a19*a24);
  casadi_real a79=(a23*a42);
  a24=(a24+a79);
  a56=(a56*a27);
  a56=(a11*a56);
  a22=(a22*a56);
  a26=(a3*a26);
  a22=(a22+a26);
  a22=(a5*a22);
  a24=(a24+a22);
  a4=sign(a4);
  a21=(a21*a4);
  a21=(a21/a37);
  a32=(a32/a37);
  a34=(a34+a34);
  a34=(a6*a34);
  a36=(a36*a34);
  a36=(a35*a36);
  a36=(a54*a36);
  a32=(a32*a36);
  a21=(a21+a32);
  a21=(a0-a21);
  a32=(a3*a21);
  a36=(a20*a32);
  a36=(a5*a36);
  a24=(a24+a36);
  a36=(a3*a24);
  a36=(a0-a36);
  a34=(a2*a36);
  a67=(a67+a34);
  a34=(a3*a42);
  a4=(a7*a34);
  a4=(a41*a4);
  a4=(a6*a4);
  a4=(a5*a4);
  a4=(a30*a4);
  a22=(a40*a36);
  a4=(a4+a22);
  a22=(a7*a34);
  a22=(a45*a22);
  a22=(a11*a22);
  a22=(a39*a22);
  a26=(a44*a34);
  a22=(a22+a26);
  a22=(a5*a22);
  a4=(a4+a22);
  a22=(a46*a42);
  a22=(a38*a22);
  a32=(a51*a32);
  a22=(a22+a32);
  a22=(a22/a50);
  a32=(a6*a42);
  a32=(a48*a32);
  a32=(a49*a32);
  a32=(a35*a32);
  a32=(a54*a32);
  a32=(a53*a32);
  a22=(a22+a32);
  a22=(a42-a22);
  a32=(a3*a22);
  a26=(a20*a32);
  a26=(a5*a26);
  a4=(a4+a26);
  a26=(a29*a4);
  a26=(a0-a26);
  a67=(a67+a26);
  a67=(a1*a67);
  if (res[0]!=0) res[0][5]=a67;
  a24=(a2*a24);
  a9=(a9+a24);
  a4=(a2*a4);
  a9=(a9+a4);
  a4=(a29*a36);
  a24=(a7*a4);
  a24=(a66*a24);
  a24=(a6*a24);
  a24=(a5*a24);
  a24=(a16*a24);
  a67=(a65*a26);
  a24=(a24+a67);
  a67=(a7*a4);
  a67=(a17*a67);
  a67=(a11*a67);
  a67=(a12*a67);
  a56=(a18*a4);
  a67=(a67+a56);
  a67=(a5*a67);
  a24=(a24+a67);
  a67=(a57*a36);
  a67=(a52*a67);
  a32=(a15*a32);
  a67=(a67+a32);
  a67=(a67/a60);
  a32=(a6*a36);
  a32=(a58*a32);
  a32=(a59*a32);
  a32=(a35*a32);
  a32=(a54*a32);
  a32=(a62*a32);
  a67=(a67+a32);
  a67=(a36-a67);
  a32=(a29*a67);
  a56=(a20*a32);
  a56=(a5*a56);
  a24=(a24+a56);
  a9=(a9+a24);
  a9=(a1*a9);
  a9=(a0-a9);
  if (res[0]!=0) res[0][6]=a9;
  a22=(a2*a22);
  a21=(a21+a22);
  a67=(a2*a67);
  a21=(a21+a67);
  a67=(a55*a26);
  a67=(a61*a67);
  a32=(a10*a32);
  a67=(a67+a32);
  a67=(a67/a33);
  a32=(a6*a26);
  a32=(a63*a32);
  a32=(a25*a32);
  a32=(a35*a32);
  a32=(a54*a32);
  a32=(a68*a32);
  a67=(a67+a32);
  a67=(a26-a67);
  a21=(a21+a67);
  a21=(a1*a21);
  if (res[0]!=0) res[0][7]=a21;
  a21=sq(a8);
  a21=(a47*a21);
  a8=sq(a8);
  a8=(a43*a8);
  a8=(a8+a14);
  a21=(a21+a8);
  a69=(a3*a69);
  a69=(a47*a69);
  a69=(a19*a69);
  a8=(a71*a42);
  a69=(a69+a8);
  a72=(a3*a72);
  a72=(a43*a72);
  a19=(a19*a72);
  a42=(a74*a42);
  a19=(a19+a42);
  a69=(a69+a19);
  a69=(a2*a69);
  a21=(a21+a69);
  a69=(a70*a34);
  a69=(a47*a69);
  a69=(a30*a69);
  a19=(a13*a36);
  a69=(a69+a19);
  a34=(a75*a34);
  a34=(a43*a34);
  a34=(a30*a34);
  a36=(a76*a36);
  a34=(a34+a36);
  a69=(a69+a34);
  a69=(a2*a69);
  a21=(a21+a69);
  a69=(a73*a4);
  a69=(a47*a69);
  a69=(a16*a69);
  a34=(a28*a26);
  a69=(a69+a34);
  a4=(a77*a4);
  a4=(a43*a4);
  a4=(a16*a4);
  a26=(a78*a26);
  a4=(a4+a26);
  a69=(a69+a4);
  a21=(a21+a69);
  a21=(a1*a21);
  if (res[0]!=0) res[0][8]=a21;
  if (res[0]!=0) res[0][9]=a64;
  a21=-7.4626865671641796e-001;
  a69=-3.7313432835820898e-001;
  a23=(a69*a23);
  a31=(a31/a37);
  a37=(a3*a31);
  a37=(a0-a37);
  a4=(a20*a37);
  a4=(a5*a4);
  a23=(a23+a4);
  a4=(a3*a23);
  a26=(a2*a4);
  a21=(a21-a26);
  a26=-9.3283582089552248e-003;
  a41=(a26*a41);
  a41=(a6*a41);
  a41=(a5*a41);
  a41=(a30*a41);
  a40=(a40*a4);
  a41=(a41-a40);
  a26=(a26*a45);
  a26=(a11*a26);
  a39=(a39*a26);
  a26=-9.3283582089552248e-004;
  a44=(a26*a44);
  a39=(a39+a44);
  a39=(a5*a39);
  a41=(a41+a39);
  a46=(a69*a46);
  a38=(a38*a46);
  a51=(a51*a37);
  a38=(a38+a51);
  a38=(a38/a50);
  a50=-7.4626865671641795e+001;
  a50=(a50*a48);
  a49=(a49*a50);
  a49=(a35*a49);
  a49=(a54*a49);
  a53=(a53*a49);
  a38=(a38+a53);
  a38=(a69-a38);
  a3=(a3*a38);
  a3=(a0+a3);
  a53=(a20*a3);
  a53=(a5*a53);
  a41=(a41+a53);
  a53=(a29*a41);
  a21=(a21-a53);
  a21=(a1*a21);
  if (res[0]!=0) res[0][10]=a21;
  a21=-1.4925373134328359e+002;
  a23=(a2*a23);
  a21=(a21-a23);
  a23=(a2*a41);
  a21=(a21-a23);
  a23=(a29*a4);
  a49=(a7*a23);
  a66=(a66*a49);
  a66=(a6*a66);
  a66=(a5*a66);
  a66=(a16*a66);
  a65=(a65*a53);
  a66=(a66+a65);
  a7=(a7*a23);
  a17=(a17*a7);
  a11=(a11*a17);
  a12=(a12*a11);
  a18=(a18*a23);
  a12=(a12+a18);
  a12=(a5*a12);
  a66=(a66+a12);
  a15=(a15*a3);
  a57=(a57*a4);
  a52=(a52*a57);
  a15=(a15-a52);
  a15=(a15/a60);
  a6=(a6*a4);
  a58=(a58*a6);
  a59=(a59*a58);
  a59=(a35*a59);
  a59=(a54*a59);
  a62=(a62*a59);
  a15=(a15-a62);
  a15=(a4+a15);
  a62=(a29*a15);
  a62=(a0-a62);
  a20=(a20*a62);
  a5=(a5*a20);
  a66=(a66-a5);
  a21=(a21+a66);
  a21=(a1*a21);
  if (res[0]!=0) res[0][11]=a21;
  a38=(a2*a38);
  a38=(a38-a31);
  a15=(a2*a15);
  a38=(a38-a15);
  a10=(a10*a62);
  a55=(a55*a53);
  a61=(a61*a55);
  a10=(a10-a61);
  a10=(a10/a33);
  a63=(a63*a41);
  a25=(a25*a63);
  a35=(a35*a25);
  a54=(a54*a35);
  a68=(a68*a54);
  a10=(a10-a68);
  a10=(a53+a10);
  a38=(a38-a10);
  a38=(a1*a38);
  a38=(a0+a38);
  if (res[0]!=0) res[0][12]=a38;
  a71=(a69*a71);
  a69=(a69*a74);
  a71=(a71+a69);
  a71=(a2*a71);
  a70=(a26*a70);
  a70=(a47*a70);
  a70=(a30*a70);
  a13=(a13*a4);
  a70=(a70-a13);
  a26=(a26*a75);
  a26=(a43*a26);
  a30=(a30*a26);
  a76=(a76*a4);
  a30=(a30-a76);
  a70=(a70+a30);
  a2=(a2*a70);
  a71=(a71+a2);
  a73=(a73*a23);
  a47=(a47*a73);
  a47=(a16*a47);
  a28=(a28*a53);
  a47=(a47+a28);
  a77=(a77*a23);
  a43=(a43*a77);
  a16=(a16*a43);
  a78=(a78*a53);
  a16=(a16+a78);
  a47=(a47+a16);
  a71=(a71-a47);
  a1=(a1*a71);
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a64;
  if (res[0]!=0) res[0][15]=a64;
  if (res[0]!=0) res[0][16]=a64;
  if (res[0]!=0) res[0][17]=a64;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a64;
  if (res[0]!=0) res[0][20]=a64;
  if (res[0]!=0) res[0][21]=a64;
  if (res[0]!=0) res[0][22]=a64;
  if (res[0]!=0) res[0][23]=a64;
  if (res[0]!=0) res[0][24]=a0;
  if (res[1]!=0) res[1][0]=a64;
  if (res[1]!=0) res[1][1]=a64;
  if (res[1]!=0) res[1][2]=a64;
  if (res[1]!=0) res[1][3]=a29;
  if (res[1]!=0) res[1][4]=a29;
  return 0;
}

CASADI_SYMBOL_EXPORT int D(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void D_incref(void) {
}

CASADI_SYMBOL_EXPORT void D_decref(void) {
}

CASADI_SYMBOL_EXPORT int D_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int D_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* D_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* D_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* D_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* D_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int D_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 80;
  return 0;
}

/* h_fun:(states[5],controls,params[3])->(h[2]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=arg[0] ? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0] ? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int h_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f8(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int h_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* h_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* h_fun_name_out(int i){
  switch (i) {
    case 0: return "h";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* h_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* h_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int h_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}

/* path_con_fun:(states[5],controls,params[3])->(path_con[]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f9(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void path_con_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void path_con_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int path_con_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int path_con_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* path_con_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_fun_name_out(int i){
  switch (i) {
    case 0: return "path_con";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int path_con_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* path_con_N_fun:(states[5],params[3])->(path_con_N[]) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_N_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f10(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT int path_con_N_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* path_con_N_fun_name_in(int i){
  switch (i) {
    case 0: return "states";
    case 1: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_N_fun_name_out(int i){
  switch (i) {
    case 0: return "path_con_N";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_N_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* path_con_N_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* obji_fun:(i0[5],i1,i2[3],i3[2],i4[2x2])->(o0) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=5.0000000000000000e-001;
  casadi_real a1=arg[4] ? arg[4][0] : 0;
  a1=sqrt(a1);
  casadi_real a2=arg[0] ? arg[0][3] : 0;
  casadi_real a3=arg[3] ? arg[3][0] : 0;
  a2=(a2-a3);
  a1=(a1*a2);
  a3=arg[4] ? arg[4][2] : 0;
  a3=sqrt(a3);
  casadi_real a4=arg[0] ? arg[0][4] : 0;
  casadi_real a5=arg[3] ? arg[3][1] : 0;
  a4=(a4-a5);
  a3=(a3*a4);
  a1=(a1+a3);
  a1=sq(a1);
  a3=arg[4] ? arg[4][1] : 0;
  a3=sqrt(a3);
  a3=(a3*a2);
  a2=arg[4] ? arg[4][3] : 0;
  a2=sqrt(a2);
  a2=(a2*a4);
  a3=(a3+a2);
  a3=sq(a3);
  a1=(a1+a3);
  a0=(a0*a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int obji_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f11(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void obji_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void obji_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int obji_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int obji_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* obji_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obji_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* obji_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* obji_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obji_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 6;
  return 0;
}

/* objN_fun:(i0[5],i1[3],i2,i3)->(o0) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=5.0000000000000000e-001;
  casadi_real a1=arg[3] ? arg[3][0] : 0;
  a1=sqrt(a1);
  casadi_real a2=arg[0] ? arg[0][4] : 0;
  casadi_real a3=arg[2] ? arg[2][0] : 0;
  a2=(a2-a3);
  a1=(a1*a2);
  a1=fabs(a1);
  a1=sq(a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int objN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f12(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void objN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void objN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int objN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int objN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* objN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* objN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* objN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* objN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int objN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 4;
  return 0;
}

/* gi_fun:(i0[5],i1,i2[3],i3[2],i4[2x2])->(o0[5],o1) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  casadi_real a1=5.0000000000000000e-001;
  casadi_real a2=arg[4] ? arg[4][0] : 0;
  a2=sqrt(a2);
  casadi_real a3=arg[0] ? arg[0][3] : 0;
  casadi_real a4=arg[3] ? arg[3][0] : 0;
  a3=(a3-a4);
  a4=(a2*a3);
  casadi_real a5=arg[4] ? arg[4][2] : 0;
  a5=sqrt(a5);
  casadi_real a6=arg[0] ? arg[0][4] : 0;
  casadi_real a7=arg[3] ? arg[3][1] : 0;
  a6=(a6-a7);
  a7=(a5*a6);
  a4=(a4+a7);
  a4=(a4+a4);
  a2=(a4*a2);
  a7=arg[4] ? arg[4][1] : 0;
  a7=sqrt(a7);
  a3=(a7*a3);
  casadi_real a8=arg[4] ? arg[4][3] : 0;
  a8=sqrt(a8);
  a6=(a8*a6);
  a3=(a3+a6);
  a3=(a3+a3);
  a7=(a3*a7);
  a2=(a2+a7);
  a2=(a1*a2);
  if (res[0]!=0) res[0][3]=a2;
  a4=(a4*a5);
  a3=(a3*a8);
  a4=(a4+a3);
  a1=(a1*a4);
  if (res[0]!=0) res[0][4]=a1;
  if (res[1]!=0) res[1][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int gi_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f13(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void gi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void gi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int gi_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int gi_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* gi_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gi_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gi_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gi_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gi_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 9;
  return 0;
}

/* gN_fun:(i0[5],i1[3],i2,i3)->(o0[5]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  a0=5.0000000000000000e-001;
  casadi_real a1=arg[3] ? arg[3][0] : 0;
  a1=sqrt(a1);
  casadi_real a2=arg[0] ? arg[0][4] : 0;
  casadi_real a3=arg[2] ? arg[2][0] : 0;
  a2=(a2-a3);
  a2=(a1*a2);
  a3=fabs(a2);
  a3=(a3+a3);
  a2=sign(a2);
  a2=(a2*a1);
  a3=(a3*a2);
  a0=(a0*a3);
  if (res[0]!=0) res[0][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int gN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f14(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void gN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void gN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int gN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int gN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* gN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* gN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 4;
  return 0;
}

/* Ji_fun:(i0[5],i1,i2[3],i3[2],i4[2x2])->(o0[2x5],o1[2]) */
static int casadi_f15(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  casadi_real a1=arg[4] ? arg[4][0] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][6]=a1;
  a1=arg[4] ? arg[4][1] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][7]=a1;
  a1=arg[4] ? arg[4][2] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][8]=a1;
  a1=arg[4] ? arg[4][3] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][9]=a1;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Ji_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f15(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void Ji_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Ji_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int Ji_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int Ji_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* Ji_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ji_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ji_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ji_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Ji_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}

/* JN_fun:(i0[5],i1[3],i2,i3)->(o0[1x5]) */
static int casadi_f16(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[3] ? arg[3][0] : 0;
  a0=sqrt(a0);
  if (res[0]!=0) res[0][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int JN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f16(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void JN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void JN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int JN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT int JN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* JN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* JN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* JN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* JN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int JN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}

/* Ci_fun:(i0[5],i1,i2[3])->(o0[0x5],o1[0]) */
static int casadi_f17(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Ci_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f17(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void Ci_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Ci_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int Ci_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int Ci_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* Ci_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ci_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ci_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* Ci_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Ci_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* CN_fun:(i0[5],i1[3])->(o0[0x5]) */
static int casadi_f18(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int CN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f18(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void CN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void CN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int CN_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT int CN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* CN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* CN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* CN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* CN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int CN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* adj_fun:(i0[5],i1,i2[3],i3[2],i4[2x2],i5[5],i6[0])->(o0[6],o1[6],o2[6]) */
static int casadi_f19(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  casadi_real a1=5.0000000000000000e-001;
  casadi_real a2=arg[4] ? arg[4][0] : 0;
  a2=sqrt(a2);
  casadi_real a3=arg[0] ? arg[0][3] : 0;
  casadi_real a4=arg[3] ? arg[3][0] : 0;
  a3=(a3-a4);
  a4=(a2*a3);
  casadi_real a5=arg[4] ? arg[4][2] : 0;
  a5=sqrt(a5);
  casadi_real a6=arg[0] ? arg[0][4] : 0;
  casadi_real a7=arg[3] ? arg[3][1] : 0;
  a6=(a6-a7);
  a7=(a5*a6);
  a4=(a4+a7);
  a4=(a4+a4);
  a2=(a4*a2);
  a7=arg[4] ? arg[4][1] : 0;
  a7=sqrt(a7);
  a3=(a7*a3);
  casadi_real a8=arg[4] ? arg[4][3] : 0;
  a8=sqrt(a8);
  a6=(a8*a6);
  a3=(a3+a6);
  a3=(a3+a3);
  a7=(a3*a7);
  a2=(a2+a7);
  a2=(a1*a2);
  if (res[0]!=0) res[0][3]=a2;
  a4=(a4*a5);
  a3=(a3*a8);
  a4=(a4+a3);
  a1=(a1*a4);
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a0;
  a1=arg[0] ? arg[0][0] : 0;
  a4=(a1+a1);
  a3=1200000.;
  a8=arg[0] ? arg[0][1] : 0;
  a5=8.3333333333333339e-004;
  a2=arg[5] ? arg[5][3] : 0;
  a7=(a5*a2);
  a6=(a8*a7);
  a6=(a3*a6);
  a4=(a4*a6);
  a6=(a1+a1);
  casadi_real a9=2400000.;
  casadi_real a10=(a8*a7);
  a10=(a9*a10);
  a6=(a6*a10);
  a4=(a4+a6);
  a6=5.0000000000000001e-003;
  a10=2.5000000000000001e-003;
  casadi_real a11=arg[2] ? arg[2][2] : 0;
  casadi_real a12=200.;
  casadi_real a13=10.;
  casadi_real a14=(a10*a8);
  a14=(a1+a14);
  casadi_real a15=(a13*a14);
  casadi_real a16=sq(a15);
  a16=(a12*a16);
  casadi_real a17=2000.;
  a16=(a16+a17);
  casadi_real a18=67.;
  a16=(a16/a18);
  casadi_real a19=(a13*a1);
  casadi_real a20=sq(a19);
  a20=(a12*a20);
  a20=(a20+a17);
  a20=(a20/a18);
  casadi_real a21=(a20*a8);
  casadi_real a22=12000.;
  casadi_real a23=(a13*a1);
  casadi_real a24=sq(a23);
  a24=(a22*a24);
  casadi_real a25=1000.;
  a24=(a24+a25);
  casadi_real a26=(a24*a1);
  a26=(a26/a18);
  a21=(a21+a26);
  a21=(a11-a21);
  a26=9.8100000000000005e+000;
  casadi_real a27=arg[2] ? arg[2][1] : 0;
  a26=(a26*a27);
  a21=(a21+a26);
  a27=10000.;
  casadi_real a28=arg[0] ? arg[0][2] : 0;
  casadi_real a29=(a27*a28);
  a29=(a29/a18);
  a21=(a21-a29);
  a21=(a10*a21);
  a21=(a8+a21);
  a29=(a16*a21);
  casadi_real a30=(a13*a14);
  casadi_real a31=sq(a30);
  a31=(a22*a31);
  a31=(a31+a25);
  casadi_real a32=(a31*a14);
  a32=(a32/a18);
  a29=(a29+a32);
  a29=(a11-a29);
  a29=(a29+a26);
  a32=fabs(a8);
  casadi_real a33=(a32*a28);
  casadi_real a34=30.;
  casadi_real a35=3.1830988618379069e-001;
  casadi_real a36=9.8480775301220802e-001;
  casadi_real a37=arg[2] ? arg[2][0] : 0;
  a37=(a18*a37);
  a36=(a36*a37);
  a37=8.5174431145629327e+001;
  a36=(a36+a37);
  a36=atan(a36);
  a35=(a35*a36);
  a36=5.9999999999999998e-001;
  a35=(a35+a36);
  a34=(a34*a35);
  a36=15.;
  a36=(a36*a35);
  a35=(a8/a6);
  a37=sq(a35);
  a37=(-a37);
  a37=exp(a37);
  casadi_real a38=(a36*a37);
  a38=(a34+a38);
  a38=(a38/a27);
  a33=(a33/a38);
  casadi_real a39=(a8-a33);
  a39=(a10*a39);
  a39=(a28+a39);
  casadi_real a40=(a27*a39);
  a40=(a40/a18);
  a29=(a29-a40);
  a29=(a10*a29);
  a29=(a8+a29);
  a40=(a6*a29);
  a40=(a1+a40);
  casadi_real a41=(a40+a40);
  casadi_real a42=(a10*a21);
  a42=(a1+a42);
  casadi_real a43=(a13*a42);
  casadi_real a44=sq(a43);
  a44=(a12*a44);
  a44=(a44+a17);
  a44=(a44/a18);
  casadi_real a45=(a44*a29);
  casadi_real a46=(a13*a42);
  casadi_real a47=sq(a46);
  a47=(a22*a47);
  a47=(a47+a25);
  casadi_real a48=(a47*a42);
  a48=(a48/a18);
  a45=(a45+a48);
  a11=(a11-a45);
  a11=(a11+a26);
  a26=fabs(a21);
  a45=(a26*a39);
  a48=(a21/a6);
  casadi_real a49=sq(a48);
  a49=(-a49);
  a49=exp(a49);
  casadi_real a50=(a36*a49);
  a50=(a34+a50);
  a50=(a50/a27);
  a45=(a45/a50);
  casadi_real a51=(a21-a45);
  a51=(a10*a51);
  a51=(a28+a51);
  casadi_real a52=(a27*a51);
  a52=(a52/a18);
  a11=(a11-a52);
  a11=(a6*a11);
  a11=(a8+a11);
  a52=(a11*a7);
  a52=(a3*a52);
  a41=(a41*a52);
  a52=(a40+a40);
  casadi_real a53=(a11*a7);
  a53=(a9*a53);
  a52=(a52*a53);
  a41=(a41+a52);
  a52=(a13*a40);
  a53=sq(a52);
  a53=(a22*a53);
  a53=(a53+a25);
  casadi_real a54=1.4925373134328358e-002;
  casadi_real a55=arg[5] ? arg[5][1] : 0;
  casadi_real a56=(a5*a55);
  casadi_real a57=(a54*a56);
  a53=(a53*a57);
  a41=(a41-a53);
  a52=(a52+a52);
  a57=(a40*a57);
  a57=(a22*a57);
  a52=(a52*a57);
  a52=(a13*a52);
  a41=(a41-a52);
  a52=(a13*a40);
  a57=(a52+a52);
  a53=(a11*a56);
  a53=(a54*a53);
  a53=(a12*a53);
  a57=(a57*a53);
  a57=(a13*a57);
  a41=(a41-a57);
  a4=(a4+a41);
  a57=arg[5] ? arg[5][0] : 0;
  a4=(a4+a57);
  a53=(a42+a42);
  casadi_real a58=2.;
  casadi_real a59=(a58*a7);
  casadi_real a60=(a29*a59);
  a60=(a3*a60);
  a53=(a53*a60);
  a60=(a42+a42);
  casadi_real a61=(a29*a59);
  a61=(a9*a61);
  a60=(a60*a61);
  a53=(a53+a60);
  a60=(a58*a56);
  a61=sq(a40);
  a61=(a3*a61);
  a61=(a61+a25);
  a61=(a61*a7);
  a40=sq(a40);
  a40=(a9*a40);
  a40=(a40*a7);
  a61=(a61+a40);
  a40=arg[5] ? arg[5][2] : 0;
  casadi_real a62=(a5*a40);
  a61=(a61+a62);
  casadi_real a63=(a11/a6);
  casadi_real a64=(a63+a63);
  a63=sq(a63);
  a63=(-a63);
  a63=exp(a63);
  casadi_real a65=1.0000000000000000e-004;
  casadi_real a66=fabs(a11);
  casadi_real a67=fabs(a29);
  casadi_real a68=(a67*a51);
  casadi_real a69=(a29/a6);
  casadi_real a70=sq(a69);
  a70=(-a70);
  a70=exp(a70);
  casadi_real a71=(a36*a70);
  a71=(a34+a71);
  a71=(a71/a27);
  a68=(a68/a71);
  casadi_real a72=(a29-a68);
  a72=(a6*a72);
  a72=(a28+a72);
  casadi_real a73=(a66*a72);
  casadi_real a74=(a36*a63);
  a34=(a34+a74);
  a34=(a34/a27);
  a73=(a73/a34);
  a73=(a73/a34);
  a73=(a73*a62);
  a73=(a65*a73);
  a73=(a36*a73);
  a63=(a63*a73);
  a64=(a64*a63);
  a64=(a12*a64);
  a61=(a61-a64);
  a11=sign(a11);
  a34=(a62/a34);
  a72=(a72*a34);
  a11=(a11*a72);
  a61=(a61-a11);
  a52=sq(a52);
  a52=(a12*a52);
  a52=(a52+a17);
  a52=(a52/a18);
  a52=(a52*a56);
  a61=(a61-a52);
  a57=(a5*a57);
  a61=(a61+a57);
  a52=(a6*a61);
  a60=(a60+a52);
  a52=(a54*a60);
  a47=(a47*a52);
  a53=(a53-a47);
  a46=(a46+a46);
  a52=(a42*a52);
  a52=(a22*a52);
  a46=(a46*a52);
  a46=(a13*a46);
  a53=(a53-a46);
  a43=(a43+a43);
  a46=(a29*a60);
  a46=(a54*a46);
  a46=(a12*a46);
  a43=(a43*a46);
  a43=(a13*a43);
  a53=(a53-a43);
  a4=(a4+a53);
  a43=(a14+a14);
  a46=(a58*a7);
  a52=(a21*a46);
  a52=(a3*a52);
  a43=(a43*a52);
  a52=(a14+a14);
  a47=(a21*a46);
  a47=(a9*a47);
  a52=(a52*a47);
  a43=(a43+a52);
  a52=(a58*a56);
  a47=sq(a42);
  a47=(a3*a47);
  a47=(a47+a25);
  a47=(a47*a59);
  a42=sq(a42);
  a42=(a9*a42);
  a42=(a42*a59);
  a47=(a47+a42);
  a42=(a58*a62);
  a66=(a66*a34);
  a34=(a54*a56);
  a34=(a27*a34);
  a66=(a66+a34);
  a34=(a6*a66);
  a42=(a42-a34);
  a47=(a47+a42);
  a69=(a69+a69);
  a68=(a68/a71);
  a68=(a68*a42);
  a68=(a65*a68);
  a68=(a36*a68);
  a70=(a70*a68);
  a69=(a69*a70);
  a69=(a12*a69);
  a47=(a47-a69);
  a29=sign(a29);
  a42=(a42/a71);
  a51=(a51*a42);
  a29=(a29*a51);
  a47=(a47-a29);
  a6=(a6*a41);
  a47=(a47+a6);
  a44=(a44*a60);
  a47=(a47-a44);
  a44=(a58*a57);
  a47=(a47+a44);
  a44=(a10*a47);
  a52=(a52+a44);
  a44=(a54*a52);
  a31=(a31*a44);
  a43=(a43-a31);
  a30=(a30+a30);
  a44=(a14*a44);
  a44=(a22*a44);
  a30=(a30*a44);
  a30=(a13*a30);
  a43=(a43-a30);
  a15=(a15+a15);
  a30=(a21*a52);
  a30=(a54*a30);
  a30=(a12*a30);
  a15=(a15*a30);
  a15=(a13*a15);
  a43=(a43-a15);
  a4=(a4+a43);
  a15=sq(a14);
  a15=(a3*a15);
  a15=(a15+a25);
  a15=(a15*a46);
  a14=sq(a14);
  a14=(a9*a14);
  a14=(a14*a46);
  a15=(a15+a14);
  a14=(a58*a62);
  a67=(a67*a42);
  a60=(a54*a60);
  a60=(a27*a60);
  a67=(a67+a60);
  a60=(a10*a67);
  a14=(a14-a60);
  a15=(a15+a14);
  a48=(a48+a48);
  a45=(a45/a50);
  a45=(a45*a14);
  a45=(a65*a45);
  a45=(a36*a45);
  a49=(a49*a45);
  a48=(a48*a49);
  a48=(a12*a48);
  a15=(a15-a48);
  a21=sign(a21);
  a14=(a14/a50);
  a39=(a39*a14);
  a21=(a21*a39);
  a15=(a15-a21);
  a53=(a10*a53);
  a15=(a15+a53);
  a16=(a16*a52);
  a15=(a15-a16);
  a16=(a58*a57);
  a15=(a15+a16);
  a16=(a10*a15);
  a56=(a56+a16);
  a16=(a54*a56);
  a24=(a24*a16);
  a4=(a4-a24);
  a23=(a23+a23);
  a16=(a1*a16);
  a22=(a22*a16);
  a23=(a23*a22);
  a23=(a13*a23);
  a4=(a4-a23);
  a19=(a19+a19);
  a23=(a8*a56);
  a23=(a54*a23);
  a23=(a12*a23);
  a19=(a19*a23);
  a13=(a13*a19);
  a4=(a4-a13);
  if (res[1]!=0) res[1][0]=a4;
  a4=sq(a1);
  a3=(a3*a4);
  a3=(a3+a25);
  a3=(a3*a7);
  a1=sq(a1);
  a9=(a9*a1);
  a9=(a9*a7);
  a3=(a3+a9);
  a3=(a3+a55);
  a3=(a3+a61);
  a3=(a3+a47);
  a26=(a26*a14);
  a52=(a54*a52);
  a52=(a27*a52);
  a26=(a26+a52);
  a52=(a10*a26);
  a62=(a62-a52);
  a3=(a3+a62);
  a35=(a35+a35);
  a33=(a33/a38);
  a33=(a33*a62);
  a65=(a65*a33);
  a36=(a36*a65);
  a37=(a37*a36);
  a35=(a35*a37);
  a12=(a12*a35);
  a3=(a3-a12);
  a8=sign(a8);
  a62=(a62/a38);
  a28=(a28*a62);
  a8=(a8*a28);
  a3=(a3-a8);
  a10=(a10*a43);
  a3=(a3+a10);
  a3=(a3+a57);
  a3=(a3+a15);
  a20=(a20*a56);
  a3=(a3-a20);
  if (res[1]!=0) res[1][1]=a3;
  a40=(a40-a66);
  a40=(a40-a67);
  a40=(a40-a26);
  a32=(a32*a62);
  a40=(a40-a32);
  a54=(a54*a56);
  a27=(a27*a54);
  a40=(a40-a27);
  if (res[1]!=0) res[1][2]=a40;
  if (res[1]!=0) res[1][3]=a2;
  a2=arg[5] ? arg[5][4] : 0;
  if (res[1]!=0) res[1][4]=a2;
  a5=(a5*a2);
  a2=(a58*a5);
  a2=(a5+a2);
  a2=(a2+a5);
  a58=(a58*a5);
  a2=(a2+a58);
  a2=(a2+a7);
  a2=(a2+a59);
  a2=(a2+a46);
  a2=(a2+a7);
  if (res[1]!=0) res[1][5]=a2;
  if (res[2]!=0) res[2][0]=a0;
  if (res[2]!=0) res[2][1]=a0;
  if (res[2]!=0) res[2][2]=a0;
  if (res[2]!=0) res[2][3]=a0;
  if (res[2]!=0) res[2][4]=a0;
  if (res[2]!=0) res[2][5]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int adj_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f19(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void adj_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adj_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int adj_fun_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT int adj_fun_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT const char* adj_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adj_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adj_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s6;
    case 5: return casadi_s0;
    case 6: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adj_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s11;
    case 1: return casadi_s11;
    case 2: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adj_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 75;
  return 0;
}

/* adjN_fun:(i0[5],i1[3],i2,i3,i4[0])->(o0[5],o1[5]) */
static int casadi_f20(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  casadi_real a1=5.0000000000000000e-001;
  casadi_real a2=arg[3] ? arg[3][0] : 0;
  a2=sqrt(a2);
  casadi_real a3=arg[0] ? arg[0][4] : 0;
  casadi_real a4=arg[2] ? arg[2][0] : 0;
  a3=(a3-a4);
  a3=(a2*a3);
  a4=fabs(a3);
  a4=(a4+a4);
  a3=sign(a3);
  a3=(a3*a2);
  a4=(a4*a3);
  a1=(a1*a4);
  if (res[0]!=0) res[0][4]=a1;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  if (res[1]!=0) res[1][3]=a0;
  if (res[1]!=0) res[1][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int adjN_fun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f20(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void adjN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adjN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT int adjN_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT int adjN_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* adjN_fun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adjN_fun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adjN_fun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adjN_fun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adjN_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 5;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
